import {
  LayoutDashboard,
  User,
  Settings,
  Briefcase,
  CheckSquare,
  TrendingUp,
  BookOpen,
  Inbox,
  CalendarDays,
  Users,
  Wallet,
  BarChart3,
  PieChart,
  LineChart,
  Target,
  Award,
  UserCircle,
  MessageCircle,
  BookOpen as KnowledgeIcon,
  Bot,
  MessageSquare,
  Package,
  Mail,
  Download,
  Users2,
  Workflow,
  FileText,
  Bell,
  ClipboardList,
  MapPin,
  Search,
  Receipt,
  BookMarked,
} from "lucide-react";

export const CORE_CLIENT_MODULES = [
  {
    key: "dashboard",
    label: "Dashboard",
    route: "/Client/Dashboard",
    clientRoute: "Dashboard",
    icon: LayoutDashboard,
    section: "Overview",
    description: "Workspace overview, summaries, and quick access.",
    isCore: true,
  },
  {
    key: "profile",
    label: "My Profile",
    route: "/Client/Profile",
    clientRoute: "Profile",
    icon: User,
    section: "Account",
    description: "Manage account details and user profile.",
    isCore: true,
  },
];

export const WORKSPACE_CLIENT_MODULES = [
  {
    key: "projects",
    label: "Projects",
    route: "/Client/Projects",
    clientRoute: "Projects",
    icon: Briefcase,
    section: "Work",
    description: "Track service delivery and implementation projects.",
  },
  {
    key: "tasks",
    label: "Tasks",
    route: "/Client/Tasks",
    clientRoute: "Tasks",
    icon: CheckSquare,
    section: "Work",
    description: "Manage assigned project tasks and execution items.",
  },
  {
    key: "deals",
    label: "Deals",
    route: "/Client/Deals",
    clientRoute: "Deals",
    icon: TrendingUp,
    section: "Work",
    description: "View deal pipeline and opportunity progress.",
  },
  {
    key: "contacts",
    label: "Contacts",
    route: "/Client/Contacts",
    clientRoute: "Contacts",
    icon: BookOpen,
    section: "Work",
    description: "Access workspace contact records.",
  },
  {
    key: "inbox",
    label: "Inbox",
    route: "/Client/Inbox",
    clientRoute: "Inbox",
    icon: Inbox,
    section: "Work",
    description: "View workspace communication and conversations.",
  },
  {
    key: "facebook_inbox",
    label: "Facebook Inbox",
    route: "/Client/Inbox/Facebook",
    clientRoute: "InboxFacebook",
    icon: MessageCircle,
    section: "Work",
    description: "View Facebook inbox conversations tied to your profile.",
  },
  {
    key: "booking",
    label: "Booking",
    route: "/Client/Booking",
    clientRoute: "Booking",
    icon: CalendarDays,
    section: "Work",
    description: "View bookings, appointments, and schedules.",
  },
  {
    key: "crm",
    label: "CRM",
    route: "/Client/CRM",
    clientRoute: "CRM",
    icon: Users,
    section: "Work",
    description: "Access customer relationship management tools.",
  },
  {
    key: "revenue",
    label: "Revenue",
    route: "/Client/Revenue",
    clientRoute: "Revenue",
    icon: Wallet,
    section: "Intelligence",
    description: "View revenue summaries and financial performance.",
  },
  {
    key: "analytics",
    label: "Analytics",
    route: "/Client/Analytics",
    clientRoute: "Analytics",
    icon: BarChart3,
    section: "Intelligence",
    description: "View reports, metrics, and workspace insights.",
  },
  {
    key: "data_analytics",
    label: "Data Analytics",
    route: "/Client/DataAnalytics",
    clientRoute: "DataAnalytics",
    icon: PieChart,
    section: "Intelligence",
    description: "Analyze workspace data and operational trends.",
  },
  {
    key: "pipeline_analytics",
    label: "Pipeline Analytics",
    route: "/Client/PipelineAnalytics",
    clientRoute: "PipelineAnalytics",
    icon: TrendingUp,
    section: "Intelligence",
    description: "Analyze pipeline movement and conversion metrics.",
  },
  {
    key: "revenue_projections",
    label: "Revenue Projections",
    route: "/Client/RevenueProjections",
    clientRoute: "RevenueProjections",
    icon: LineChart,
    section: "Intelligence",
    description: "Forecast revenue and expected performance.",
  },
  {
    key: "predictive",
    label: "Predictive",
    route: "/Client/Predictive",
    clientRoute: "Predictive",
    icon: Target,
    section: "Intelligence",
    description: "Access predictive insights and recommendations.",
  },
  {
    key: "leaderboard",
    label: "Leaderboard",
    route: "/Client/Leaderboard",
    clientRoute: "Leaderboard",
    icon: Award,
    section: "Intelligence",
    description: "View performance rankings and activity leaders.",
  },
  {
    key: "customer_portal",
    label: "Customer Portal",
    route: "/Client/CustomerPortal",
    clientRoute: "CustomerPortal",
    icon: UserCircle,
    section: "Customer",
    description: "Access customer-facing workspace resources.",
  },
  {
    key: "feedback_portal",
    label: "Feedback Portal",
    route: "/Client/FeedbackPortal",
    clientRoute: "FeedbackPortal",
    icon: MessageCircle,
    section: "Customer",
    description: "Submit and review feedback.",
  },
  {
    key: "knowledge_base",
    label: "Knowledge Base",
    route: "/Client/KnowledgeBase",
    clientRoute: "KnowledgeBase",
    icon: KnowledgeIcon,
    section: "Customer",
    description: "Access documentation and knowledge resources.",
  },
  {
    key: "chatbot",
    label: "Chatbot",
    route: "/Client/Chatbot",
    clientRoute: "Chatbot",
    icon: Bot,
    section: "Customer",
    description: "Access chatbot configuration and support tools.",
  },
  {
    key: "facebook_connect",
    label: "Facebook Connect",
    route: "/Client/FacebookConnect",
    clientRoute: "FacebookConnect",
    icon: MessageSquare,
    section: "Customer",
    description: "Connect and manage Facebook-related communication.",
  },
  {
    key: "inventory",
    label: "Inventory",
    description: "Track categories, items, stock movements, and low-stock alerts.",
    route: "/Client/Inventory",
    icon: "Boxes",
    section: "Operations",
    status: "active",
    clientVisible: true,
  },
  {
    key: "google_maps_leads",
    label: "Google Maps Leads",
    route: "/Client/GoogleMapsLeads",
    clientRoute: "GoogleMapsLeads",
    icon: MapPin,
    section: "Marketing",
    description: "Find & enrich local business leads from Google Maps using AI.",
  },
  {
    key: "marketing",
    label: "Marketing",
    route: "/Client/Marketing",
    clientRoute: "Marketing",
    icon: Mail,
    section: "Marketing",
    description: "Access marketing campaigns, leads, and collateral tools.",
  },
  {
    key: "marketing_collateral",
    label: "Marketing Collateral",
    route: "/Client/MarketingCollateral",
    clientRoute: "MarketingCollateral",
    icon: FileText,
    section: "Marketing",
    description: "Store and manage embedded marketing assets.",
  },
  {
    key: "invoicing",
    label: "Invoicing",
    route: "/Client/Invoicing",
    clientRoute: "Invoicing",
    icon: Receipt,
    section: "Finance",
    description: "View your invoices, quotes, payments, and billing status.",
  },
  {
    key: "accounting",
    label: "Financial Overview",
    route: "/Client/Accounting",
    clientRoute: "Accounting",
    icon: BookMarked,
    section: "Finance",
    description: "View P&L, budget utilization, and financial KPIs.",
  },
  {
    key: "data_export",
    label: "Data Export",
    route: "/Client/DataExport",
    clientRoute: "DataExport",
    icon: Download,
    section: "Operations",
    description: "Export workspace data and reports.",
  },
  {
    key: "team",
    label: "Team",
    route: "/Client/Team",
    clientRoute: "Team",
    icon: Users2,
    section: "Manage",
    description: "View and manage workspace team members.",
  },
  {
    key: "workflows",
    label: "Workflows",
    route: "/Client/Workflows",
    clientRoute: "Workflows",
    icon: Workflow,
    section: "Manage",
    description: "View workspace automations and workflows.",
  },
  {
    key: "reports",
    label: "Reports",
    route: "/Client/Reports",
    clientRoute: "Reports",
    icon: FileText,
    section: "Manage",
    description: "Access workspace reports.",
  },
  {
    key: "notifications",
    label: "Notifications",
    route: "/Client/Notifications",
    clientRoute: "Notifications",
    icon: Bell,
    section: "Manage",
    description: "View workspace alerts and notifications.",
  },
  {
    key: "audit_logs",
    label: "Audit Logs",
    route: "/Client/AuditLogs",
    clientRoute: "AuditLogs",
    icon: ClipboardList,
    section: "Manage",
    description: "Review workspace activity history.",
  },
  {
    key: "settings",
    label: "Settings",
    route: "/Client/Settings",
    clientRoute: "Settings",
    icon: Settings,
    section: "Manage",
    description: "Manage workspace settings.",
  },
];

export const ALL_CLIENT_MODULES = [
  ...CORE_CLIENT_MODULES,
  ...WORKSPACE_CLIENT_MODULES,
];

export function getModuleByKey(moduleKey) {
  return ALL_CLIENT_MODULES.find((module) => module.key === moduleKey);
}

export function groupModulesBySection(modules) {
  return modules.reduce((sections, module) => {
    const section = module.section || "Other";

    if (!sections[section]) {
      sections[section] = [];
    }

    sections[section].push(module);
    return sections;
  }, {});
}
