import { useState, useEffect } from "react";
import { 
  Card, CardContent, CardHeader, CardTitle,
  Button, Badge, Input, Select, SelectItem,
  Dialog, DialogHeader, DialogFooter, DialogTitle, DialogContent, Label, Textarea, AIAssistant
} from "../../components/admin/ui";
import { 
  Plus, FileText, Download, Calendar, Play, Brain, Sparkles, TrendingUp, 
  BarChart3, Clock, CheckCircle, AlertTriangle, Eye, Settings, Zap
} from "lucide-react";
import { aiModules } from "../../services/ai";
import { supabase } from "../../config/supabaseClient";

export default function AdminReports() {
  const [reports, setReports] = useState([]);
  const [reportMetrics, setReportMetrics] = useState(null);
  const [aiInsights, setAiInsights] = useState(null);
  const [autoGeneratedReports, setAutoGeneratedReports] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [selectedReport, setSelectedReport] = useState(null);
  const [showNewReportDialog, setShowNewReportDialog] = useState(false);
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);

  useEffect(() => {
    fetchReportsData();
  }, []);

  const fetchReportsData = async () => {
    try {
      setIsLoading(true);
      
      // Fetch reports and related data
      const [reportsData, metricsData] = await Promise.all([
        supabase.from('reports').select('*').order('created_at', { ascending: false }),
        fetchReportMetrics()
      ]);

      setReports(reportsData.data || []);
      setReportMetrics(metricsData);
      setAutoGeneratedReports(generateAutoReports());

      // Generate AI insights
      const insights = await aiModules.analyzeReportingData({
        reports: reportsData.data || [],
        metrics: metricsData,
        usage: generateUsageData()
      });
      setAiInsights(insights);

    } catch (error) {
      console.error('Error fetching reports data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const fetchReportMetrics = async () => {
    // Mock metrics - in real implementation would fetch from database
    return {
      totalReports: 24,
      activeReports: 18,
      scheduledReports: 8,
      autoGenerated: 12,
      monthlyRuns: 156,
      avgRunTime: 45,
      errorRate: 2.3,
      popularTypes: {
        financial: 8,
        sales: 6,
        performance: 5,
        compliance: 3,
        custom: 2
      }
    };
  };

  const generateUsageData = () => ({
    dailyViews: [45, 52, 38, 65, 48, 72, 58],
    weeklyDownloads: [234, 189, 267, 198, 245, 312],
    topUsers: ['admin@hermes.com', 'john@hermes.com', 'sarah@hermes.com'],
    peakUsage: 'Tuesday 2-4 PM'
  });

  const generateAutoReports = () => [
    {
      id: 'auto-1',
      name: 'AI Executive Summary',
      type: 'executive',
      description: 'Automated executive dashboard summary with AI insights',
      schedule: 'daily',
      nextRun: 'Today 9:00 AM',
      aiGenerated: true,
      confidence: 95
    },
    {
      id: 'auto-2', 
      name: 'Revenue Forecast Report',
      type: 'financial',
      description: 'AI-powered revenue forecasting with trend analysis',
      schedule: 'weekly',
      nextRun: 'Monday 8:00 AM',
      aiGenerated: true,
      confidence: 88
    },
    {
      id: 'auto-3',
      name: 'Performance Insights',
      type: 'performance',
      description: 'Team performance analysis with AI recommendations',
      schedule: 'monthly',
      nextRun: '1st of month',
      aiGenerated: true,
      confidence: 92
    }
  ];

  const getTypeColor = (type) => {
    const colors = {
      sales: "bg-[var(--brand-cyan)]",
      revenue: "bg-[var(--success)]",
      performance: "bg-[var(--brand-gold)]",
      financial: "bg-[var(--success)]",
      executive: "bg-indigo-500",
      compliance: "bg-[var(--danger)]",
      custom: "bg-[var(--text-muted)]"
    };
    return colors[type] || "bg-[var(--text-muted)]";
  };

  const getStatusColor = (status) => {
    const colors = {
      active: "bg-[var(--success-soft)] text-[var(--success)]",
      scheduled: "bg-[var(--brand-cyan-soft)] text-[var(--brand-cyan)]",
      draft: "bg-[var(--brand-gold-soft)] text-[var(--brand-gold)]",
      archived: "bg-[var(--hover-bg)] text-[var(--text-secondary)]"
    };
    return colors[status] || "bg-[var(--hover-bg)]";
  };

  const filteredReports = [...reports, ...autoGeneratedReports].filter(r => 
    r.name.toLowerCase().includes(search.toLowerCase())
  );

  const generateAIReport = async (template) => {
    try {
      setIsGeneratingReport(true);
      const reportData = await aiModules.generateAutomatedReport({
        template,
        metrics: reportMetrics,
        historicalData: reports.slice(0, 10)
      });
      
      // Add to reports list
      const newReport = {
        id: `ai-${Date.now()}`,
        name: reportData.title,
        type: template.type,
        description: reportData.description,
        aiGenerated: true,
        generatedAt: new Date().toISOString(),
        confidence: reportData.confidence,
        insights: reportData.insights
      };
      
      setReports(prev => [newReport, ...prev]);
      setSelectedReport(newReport);
      
    } catch (error) {
      console.error('Error generating AI report:', error);
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const runReport = async (reportId) => {
    // Simulate running a report
    const report = filteredReports.find(r => r.id === reportId);
    if (report) {
      report.lastRun = new Date().toISOString().split('T')[0];
      report.status = 'running';
      setReports([...reports]);
      
      // Simulate completion
      setTimeout(() => {
        report.status = 'completed';
        setReports([...reports]);
      }, 2000);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-8 h-8 border-4 border-[#c9a84c] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Reports Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-[var(--text-primary)]">AI-Powered Reports</h1>
          <p className="text-[var(--text-secondary)]">Automated reporting with AI insights and analytics</p>
        </div>
        <div className="flex gap-3">
          <Button variant="secondary" icon={Download}>
            Export All Reports
          </Button>
          <Button icon={Plus} onClick={() => setShowNewReportDialog(true)}>
            Create AI Report
          </Button>
        </div>
      </div>

      {/* Report Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Total Reports</p>
                <p className="text-2xl font-bold text-[var(--text-primary)]">{reportMetrics?.totalReports || 0}</p>
                <p className="text-sm text-[var(--text-muted)] mt-2">
                  {reportMetrics?.activeReports || 0} active
                </p>
              </div>
              <div className="w-12 h-12 bg-[var(--brand-cyan-soft)] rounded-2xl flex items-center justify-center">
                <FileText className="w-6 h-6 text-[var(--brand-cyan)]" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[var(--text-secondary)]">AI Generated</p>
                <p className="text-2xl font-bold text-[var(--brand-gold)]">{reportMetrics?.autoGenerated || 0}</p>
                <p className="text-sm text-[var(--text-muted)] mt-2">
                  {autoGeneratedReports.length} automated
                </p>
              </div>
              <div className="w-12 h-12 bg-[var(--brand-gold-soft)] rounded-2xl flex items-center justify-center">
                <Brain className="w-6 h-6 text-[var(--brand-gold)]" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Monthly Runs</p>
                <p className="text-2xl font-bold text-[var(--text-primary)]">{reportMetrics?.monthlyRuns || 0}</p>
                <p className="text-sm text-[var(--text-muted)] mt-2">
                  {reportMetrics?.avgRunTime}s avg time
                </p>
              </div>
              <div className="w-12 h-12 bg-[var(--success-soft)] rounded-2xl flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-[var(--success)]" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-[var(--text-secondary)]">Error Rate</p>
                <p className="text-2xl font-bold text-[var(--danger)]">{reportMetrics?.errorRate || 0}%</p>
                <p className="text-sm text-[var(--text-muted)] mt-2">
                  Last 30 days
                </p>
              </div>
              <div className="w-12 h-12 bg-[var(--danger-soft)] rounded-2xl flex items-center justify-center">
                <AlertTriangle className="w-6 h-6 text-[var(--danger)]" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search and Filters */}
      <div className="flex items-center gap-4">
        <div className="relative flex-1 max-w-sm">
          <FileText className="absolute left-2.5 top-2.5 h-4 w-4 text-[var(--text-muted)]" />
          <Input 
            type="search" 
            placeholder="Search reports..." 
            className="pl-8" 
            value={search} 
            onChange={e => setSearch(e.target.value)} 
          />
        </div>
        <Select value="all" className="w-[150px]">
          <SelectItem value="all">All Types</SelectItem>
          <SelectItem value="financial">Financial</SelectItem>
          <SelectItem value="sales">Sales</SelectItem>
          <SelectItem value="performance">Performance</SelectItem>
          <SelectItem value="executive">Executive</SelectItem>
        </Select>
      </div>

      {/* AI-Generated Reports Section */}
      <Card className="bg-gradient-to-br from-[var(--brand-gold-soft)] via-[var(--bg-card)] to-[var(--brand-cyan-soft)] border border-[var(--brand-gold-border)]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Brain className="w-5 h-5 text-[var(--brand-gold)]" />
            AI Automated Reports
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {autoGeneratedReports.map(report => (
              <Card key={report.id} className="border-[var(--brand-gold-border)]">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <CardTitle className="text-lg font-semibold">{report.name}</CardTitle>
                    <div className="flex items-center gap-1">
                      <Brain className="w-4 h-4 text-[var(--brand-gold)]" />
                      <Badge variant="info" className="text-xs">AI</Badge>
                    </div>
                  </div>
                  <p className="text-sm text-[var(--text-secondary)]">{report.description}</p>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2 text-sm text-[var(--text-secondary)] mb-4">
                    <div className="flex items-center gap-2">
                      <Clock className="h-4 w-4" />
                      <span>Next: {report.nextRun}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Zap className="h-4 w-4" />
                      <span>Confidence: {report.confidence}%</span>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="flex-1"
                      onClick={() => generateAIReport(report)}
                      disabled={isGeneratingReport}
                    >
                      <Sparkles className="mr-2 h-4 w-4" /> Generate Now
                    </Button>
                    <Button variant="outline" size="sm" className="flex-1">
                      <Settings className="mr-2 h-4 w-4" /> Configure
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* All Reports Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {filteredReports.length === 0 ? (
          <div className="col-span-3 text-center py-12 text-[var(--text-muted)]">No reports found</div>
        ) : (
          filteredReports.map(report => (
            <Card key={report.id} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <CardTitle className="text-lg font-semibold">{report.name}</CardTitle>
                  <div className="flex items-center gap-2">
                    {report.aiGenerated && (
                      <div className="flex items-center gap-1">
                        <Brain className="w-4 h-4 text-[var(--brand-gold)]" />
                        <Badge variant="info" className="text-xs">AI</Badge>
                      </div>
                    )}
                    <Badge className={`${getTypeColor(report.type)} text-white capitalize`}>
                      {report.type}
                    </Badge>
                  </div>
                </div>
                {report.description && (
                  <p className="text-sm text-[var(--text-secondary)] mt-1">{report.description}</p>
                )}
              </CardHeader>
              <CardContent>
                <div className="space-y-2 text-sm text-[var(--text-secondary)] mb-4">
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4" />
                    <span>Schedule: {report.schedule || 'Manual'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4" />
                    <span>Last run: {report.lastRun || 'Never'}</span>
                  </div>
                  {report.confidence && (
                    <div className="flex items-center gap-2">
                      <BarChart3 className="h-4 w-4" />
                      <span>Confidence: {report.confidence}%</span>
                    </div>
                  )}
                </div>
                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="flex-1"
                    onClick={() => runReport(report.id)}
                  >
                    <Play className="mr-2 h-4 w-4" /> Run
                  </Button>
                  <Button variant="outline" size="sm" className="flex-1">
                    <Eye className="mr-2 h-4 w-4" /> View
                  </Button>
                  <Button variant="outline" size="sm">
                    <Download className="mr-2 h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* AI Reporting Intelligence */}
      <Card className="bg-gradient-to-br from-[var(--brand-cyan-soft)] via-[var(--bg-card)] to-[var(--success-soft)] border border-[var(--brand-cyan-border)]">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Brain className="w-5 h-5 text-[var(--brand-cyan)]" />
            AI Reporting Intelligence
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-[var(--brand-cyan)]" />
                Key Insights
              </h4>
              <div className="space-y-2">
                {aiInsights?.insights?.slice(0, 3).map((insight, index) => (
                  <div key={index} className="flex items-start gap-2">
                    <CheckCircle className="w-4 h-4 text-[var(--success)] mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-[var(--text-secondary)]">{insight}</p>
                  </div>
                )) || (
                  <p className="text-sm text-[var(--text-muted)]">Analyzing reporting patterns...</p>
                )}
              </div>
            </div>
            
            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-[var(--success)]" />
                Usage Analytics
              </h4>
              <div className="space-y-2">
                <div className="p-3 bg-[var(--bg-card)] rounded-2xl">
                  <p className="text-sm font-medium text-[var(--text-primary)]">Peak Usage Time</p>
                  <p className="text-xs text-[var(--text-secondary)] mt-1">{aiInsights?.usage?.peakTime || 'Tuesday 2-4 PM'}</p>
                </div>
                <div className="p-3 bg-[var(--bg-card)] rounded-2xl">
                  <p className="text-sm font-medium text-[var(--text-primary)]">Most Popular Type</p>
                  <p className="text-xs text-[var(--text-secondary)] mt-1">{aiInsights?.usage?.popularType || 'Financial Reports'}</p>
                </div>
              </div>
            </div>

            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-3 flex items-center gap-2">
                <Zap className="w-4 h-4 text-[var(--brand-gold)]" />
                AI Recommendations
              </h4>
              <div className="space-y-2">
                {aiInsights?.recommendations?.slice(0, 3).map((rec, index) => (
                  <div key={index} className="flex items-start gap-2">
                    <Brain className="w-4 h-4 text-[var(--brand-gold)] mt-0.5 flex-shrink-0" />
                    <p className="text-sm text-[var(--text-secondary)]">{rec}</p>
                  </div>
                )) || (
                  <p className="text-sm text-[var(--text-muted)]">Generating recommendations...</p>
                )}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* AI Assistant */}
      <AIAssistant 
        context="reports"
        data={{ reports, reportMetrics, autoGeneratedReports, aiInsights }}
      />
    </div>
  );
}
