import { useState, useEffect, useMemo, useRef, useCallback } from "react";
import { supabase } from "../../config/supabaseClient.js";
import {
  TrendingUp,
  Users,
  DollarSign,
  Target,
  Zap,
  FileSpreadsheet,
  FileText,
  Sparkles,
  ArrowUpRight,
  ArrowDownRight,
  Brain,
  Send,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Search,
  Filter,
  X,
  Activity,
  AlertTriangle,
  CheckCircle2,
  Lightbulb,
  BarChart3,
  PieChart,
  LineChart,
  Calendar,
  Clock,
  Globe,
  Megaphone,
  ShieldCheck,
  RefreshCw,
} from "lucide-react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  PieChart as RePieChart,
  Pie,
  Cell,
  FunnelChart,
  Funnel,
  LabelList,
  BarChart,
  Bar,
  LineChart as ReLineChart,
  Line,
} from "recharts";

/* ─── Design Tokens ──────────────────────────────────────────── */
const THEME = {
  colors: {
    primary: "var(--brand-cyan)",
    revenue: "#3b82f6",
    users: "#10b981",
    conversion: "#f59e0b",
    growth: "var(--brand-gold)",
    danger: "#ef4444",
    success: "#22c55e",
    warning: "#f59e0b",
    info: "#3b82f6",
    purple: "#8b5cf6",
    pink: "#ec4899",
    background: "var(--hover-bg)",
    surface: "#ffffff",
    border: "var(--border-color)",
    text: { primary: "var(--text-primary)", secondary: "var(--text-secondary)", muted: "var(--text-muted)" },
  },
  spacing: { xs: "4px", sm: "8px", md: "12px", lg: "16px", xl: "24px", "2xl": "32px" },
  borderRadius: { sm: "8px", md: "12px", lg: "16px", xl: "20px" },
};

const TRAFFIC_COLORS = ["var(--brand-cyan)", "var(--success)", "var(--brand-gold)", "var(--brand-gold-hover)"];
const RANGES = [{ key: "7d", label: "7D" }, { key: "30d", label: "30D" }, { key: "90d", label: "90D" }, { key: "custom", label: "Custom" }];
const RANGE_LABELS = { "7d": "Last 7 days", "30d": "Last 30 days", "90d": "Last 90 days", "custom": "Custom Range" };
const QUICK_PROMPTS = [
  "What's driving revenue growth?",
  "Predict next month's conversion rate",
  "Which metric needs attention?",
  "Summarise performance this period",
];
const PAGE_SIZE = 20;

/* ─── Executive AI Summary Component ─────────────────────────── */
function ExecutiveSummary({ metrics, timeRange }) {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);

  const generateSummary = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/ai/executive-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ dashboardData: { metrics, timeRange } }),
      });
      if (!response.ok) throw new Error('Failed to generate summary');
      const data = await response.json();
      setSummary(data);
    } catch (err) {
      console.error('Summary error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    generateSummary();
  }, [metrics, timeRange]);

  return (
    <div style={{
      background: "linear-gradient(135deg, var(--brand-cyan-soft), var(--brand-gold-soft))",
      borderRadius: THEME.borderRadius.xl,
      padding: THEME.spacing.xl,
      marginBottom: THEME.spacing.xl,
      border: "1px solid var(--border-color)",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)"
    }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: THEME.spacing.lg }}>
        <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.md }}>
          <div style={{
            width: "48px", height: "48px", borderRadius: THEME.borderRadius.lg,
            background: "rgba(255, 255, 255, 0.2)", display: "flex", alignItems: "center", justifyContent: "center"
          }}>
            <Brain size={24} color="white" />
          </div>
          <div>
            <h2 style={{ fontSize: "18px", fontWeight: "700", color: "white", margin: 0 }}>Executive AI Summary</h2>
            <p style={{ fontSize: "13px", color: "rgba(255, 255, 255, 0.8)", margin: 0 }}>
              {RANGE_LABELS[timeRange]} • Generated by AI
            </p>
          </div>
        </div>
        <button
          onClick={generateSummary}
          disabled={loading}
          style={{
            display: "flex", alignItems: "center", gap: THEME.spacing.sm,
            padding: THEME.spacing.sm + " " + THEME.spacing.lg,
            borderRadius: THEME.borderRadius.md, border: "none",
            background: "rgba(255, 255, 255, 0.2)", color: "white",
            fontSize: "13px", fontWeight: "500", cursor: loading ? "not-allowed" : "pointer",
            opacity: loading ? 0.7 : 1
          }}
        >
          {loading ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <RefreshCw size={14} />}
          {loading ? "Generating..." : "Refresh"}
        </button>
      </div>

      {loading ? (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "40px", color: "white" }}>
          <Loader2 size={32} style={{ animation: "spin 1s linear infinite" }} />
        </div>
      ) : summary?.error ? (
        <div style={{ padding: "20px", background: "rgba(239, 68, 68, 0.1)", borderRadius: THEME.borderRadius.md, color: "#b91c1c" }}>
          Failed to generate summary: {summary.error}
        </div>
      ) : summary ? (
        <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr", gap: THEME.spacing.xl }}>
          <div>
            <h3 style={{ fontSize: "14px", fontWeight: "600", color: "white", marginBottom: THEME.spacing.sm, opacity: 0.9 }}>Summary</h3>
            <p style={{ fontSize: "14px", color: "rgba(255, 255, 255, 0.9)", lineHeight: 1.6, margin: 0 }}>{summary.summary}</p>
          </div>
          <div>
            <h3 style={{ fontSize: "14px", fontWeight: "600", color: "#86efac", marginBottom: THEME.spacing.sm }}>Highlights</h3>
            <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
              {summary.highlights?.map((h, i) => (
                <li key={i} style={{ fontSize: "13px", color: "rgba(255, 255, 255, 0.85)", marginBottom: "6px", display: "flex", alignItems: "flex-start", gap: "6px" }}>
                  <CheckCircle2 size={14} style={{ flexShrink: 0, marginTop: "2px" }} />
                  {h}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h3 style={{ fontSize: "14px", fontWeight: "600", color: "#fdba74", marginBottom: THEME.spacing.sm }}>Concerns</h3>
            <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
              {summary.concerns?.map((c, i) => (
                <li key={i} style={{ fontSize: "13px", color: "rgba(255, 255, 255, 0.85)", marginBottom: "6px", display: "flex", alignItems: "flex-start", gap: "6px" }}>
                  <AlertTriangle size={14} style={{ flexShrink: 0, marginTop: "2px" }} />
                  {c}
                </li>
              ))}
            </ul>
          </div>
        </div>
      ) : (
        <div style={{ padding: "20px", color: "rgba(255, 255, 255, 0.7)" }}>
          Click "Refresh" to generate AI-powered executive summary
        </div>
      )}
    </div>
  );
}

/* ─── Business Health Score Component ─────────────────────────── */
function BusinessHealthScore({ metrics }) {
  const calculateScore = () => {
    let score = 0;
    const weights = { revenue: 30, growth: 25, conversion: 25, users: 20 };
    
    // Revenue score (0-30)
    const revenueScore = Math.min(30, (metrics.total_revenue / 1000000) * 30);
    score += revenueScore;
    
    // Growth score (0-25)
    const growthScore = Math.min(25, Math.max(0, metrics.growth_rate * 2.5));
    score += growthScore;
    
    // Conversion score (0-25)
    const conversionScore = Math.min(25, metrics.conversion_rate * 2.5);
    score += conversionScore;
    
    // Users score (0-20)
    const usersScore = Math.min(20, (metrics.active_users / 1000) * 20);
    score += usersScore;
    
    return Math.round(score);
  };

  const score = calculateScore();
  const getScoreColor = () => {
    if (score >= 80) return THEME.colors.success;
    if (score >= 60) return THEME.colors.warning;
    if (score >= 40) return THEME.colors.conversion;
    return THEME.colors.danger;
  };

  const getScoreLabel = () => {
    if (score >= 80) return "Excellent";
    if (score >= 60) return "Good";
    if (score >= 40) return "Fair";
    return "Needs Attention";
  };

  return (
    <div style={{
      background: "var(--bg-card)", borderRadius: THEME.borderRadius.lg,
      padding: THEME.spacing.xl, border: "1px solid var(--border-color)",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)"
    }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: THEME.spacing.lg }}>
        <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.md }}>
          <div style={{
            width: "40px", height: "40px", borderRadius: THEME.borderRadius.md,
            background: `${getScoreColor()}15`, display: "flex", alignItems: "center", justifyContent: "center"
          }}>
            <ShieldCheck size={20} color={getScoreColor()} />
          </div>
          <div>
            <h3 style={{ fontSize: "16px", fontWeight: "600", color: THEME.colors.text.primary, margin: 0 }}>Business Health</h3>
            <p style={{ fontSize: "12px", color: THEME.colors.text.muted, margin: 0 }}>Overall performance score</p>
          </div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontSize: "32px", fontWeight: "700", color: getScoreColor(), lineHeight: 1 }}>{score}</div>
          <div style={{ fontSize: "12px", fontWeight: "500", color: getScoreColor() }}>{getScoreLabel()}</div>
        </div>
      </div>
      <div style={{ height: "8px", background: "var(--hover-bg)", borderRadius: "4px", overflow: "hidden" }}>
        <div style={{
          height: "100%", width: `${score}%`, background: getScoreColor(),
          borderRadius: "4px", transition: "width 0.5s ease"
        }} />
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", marginTop: THEME.spacing.sm, fontSize: "11px", color: THEME.colors.text.muted }}>
        <span>Revenue</span>
        <span>Growth</span>
        <span>Conversion</span>
        <span>Users</span>
      </div>
    </div>
  );
}

/* ─── Revenue Forecast Component ───────────────────────────────── */
function RevenueForecast({ revenueChart, timeRange }) {
  const [forecast, setForecast] = useState(null);
  const [loading, setLoading] = useState(false);

  const calculateForecast = () => {
    setLoading(true);
    setTimeout(() => {
      const data = revenueChart;
      if (!data || data.length < 2) {
        setForecast(null);
        setLoading(false);
        return;
      }

      const n = data.length;
      const x = data.map((_, i) => i);
      const y = data.map((d) => d.value);
      const sx = x.reduce((a, b) => a + b, 0);
      const sy = y.reduce((a, b) => a + b, 0);
      const sxy = x.reduce((t, xi, i) => t + xi * y[i], 0);
      const sx2 = x.reduce((t, xi) => t + xi * xi, 0);
      const slope = (n * sxy - sx * sy) / (n * sx2 - sx * sx);
      const intercept = (sy - slope * sx) / n;
      const yMean = sy / n;
      const ssTotal = y.reduce((t, yi) => t + (yi - yMean) ** 2, 0);
      const ssRes = y.reduce((t, yi, i) => t + (yi - (slope * x[i] + intercept)) ** 2, 0);
      const r2 = ssTotal > 0 ? 1 - ssRes / ssTotal : 0;

      const days = timeRange === "7d" ? 7 : timeRange === "30d" ? 30 : 90;
      const current = data.at(-1)?.value || 0;
      const projected = current + slope * days;
      const change = ((projected - current) / current) * 100;
      const confidence = Math.round(60 + Math.min(25, r2 * 25) + Math.min(15, (n / 30) * 15));

      setForecast({
        projectedRevenue: Math.max(0, projected),
        change,
        confidence,
        trend: slope > 0 ? "upward" : slope < 0 ? "downward" : "stable"
      });
      setLoading(false);
    }, 1000);
  };

  useEffect(() => {
    calculateForecast();
  }, [revenueChart, timeRange]);

  return (
    <div style={{
      background: "var(--bg-card)", borderRadius: THEME.borderRadius.lg,
      padding: THEME.spacing.xl, border: "1px solid var(--border-color)",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)"
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.md, marginBottom: THEME.spacing.lg }}>
        <div style={{
          width: "40px", height: "40px", borderRadius: THEME.borderRadius.md,
          background: `${THEME.colors.purple}15`, display: "flex", alignItems: "center", justifyContent: "center"
        }}>
          <TrendingUp size={20} color={THEME.colors.purple} />
        </div>
        <div>
          <h3 style={{ fontSize: "16px", fontWeight: "600", color: THEME.colors.text.primary, margin: 0 }}>Revenue Forecast</h3>
          <p style={{ fontSize: "12px", color: THEME.colors.text.muted, margin: 0 }}>AI-powered projection</p>
        </div>
      </div>

      {loading ? (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "20px" }}>
          <Loader2 size={24} style={{ animation: "spin 1s linear infinite", color: THEME.colors.text.muted }} />
        </div>
      ) : forecast ? (
        <div>
          <div style={{ marginBottom: THEME.spacing.lg }}>
            <p style={{ fontSize: "12px", color: THEME.colors.text.muted, marginBottom: "4px" }}>Projected Revenue</p>
            <div style={{ display: "flex", alignItems: "baseline", gap: THEME.spacing.sm }}>
              <span style={{ fontSize: "28px", fontWeight: "700", color: THEME.colors.text.primary }}>
                {fmt(forecast.projectedRevenue)}
              </span>
              <span style={{
                fontSize: "14px", fontWeight: "600",
                color: forecast.change >= 0 ? THEME.colors.success : THEME.colors.danger
              }}>
                {forecast.change >= 0 ? "+" : ""}{forecast.change.toFixed(1)}%
              </span>
            </div>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.lg, marginBottom: THEME.spacing.lg }}>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: "12px", color: THEME.colors.text.muted, marginBottom: "4px" }}>Confidence</p>
              <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.sm }}>
                <div style={{ flex: 1, height: "6px", background: "var(--hover-bg)", borderRadius: "3px", overflow: "hidden" }}>
                  <div style={{ width: `${forecast.confidence}%`, height: "100%", background: THEME.colors.purple, borderRadius: "3px" }} />
                </div>
                <span style={{ fontSize: "13px", fontWeight: "600", color: THEME.colors.text.primary }}>{forecast.confidence}%</span>
              </div>
            </div>
            <div>
              <p style={{ fontSize: "12px", color: THEME.colors.text.muted, marginBottom: "4px" }}>Trend</p>
              <span style={{
                fontSize: "13px", fontWeight: "600", padding: "4px 10px", borderRadius: "12px",
                background: forecast.trend === "upward" ? "var(--success-soft)" : forecast.trend === "downward" ? "var(--danger-soft)" : "var(--hover-bg)",
                color: forecast.trend === "upward" ? THEME.colors.success : forecast.trend === "downward" ? THEME.colors.danger : THEME.colors.text.secondary
              }}>
                {forecast.trend.charAt(0).toUpperCase() + forecast.trend.slice(1)}
              </span>
            </div>
          </div>

          <button
            onClick={calculateForecast}
            style={{
              width: "100%", padding: THEME.spacing.sm, borderRadius: THEME.borderRadius.md,
              border: "1px solid var(--border-color)", background: "var(--hover-bg)",
              color: THEME.colors.text.secondary, fontSize: "13px", fontWeight: "500", cursor: "pointer"
            }}
          >
            Recalculate Forecast
          </button>
        </div>
      ) : (
        <div style={{ padding: "20px", textAlign: "center", color: THEME.colors.text.muted }}>
          Insufficient data for forecast
        </div>
      )}
    </div>
  );
}

/* ─── Enhanced KPI Card Component ───────────────────────────────── */
function EnhancedKpiCard({ label, value, delta, target, icon: Icon, color, previousValue }) {
  const isUp = delta >= 0;
  const progress = target ? Math.min(100, (value / target) * 100) : null;
  const status = progress ? (progress >= 100 ? "On Track" : progress >= 75 ? "Good" : progress >= 50 ? "At Risk" : "Critical") : null;
  const statusColor = progress ? (progress >= 100 ? THEME.colors.success : progress >= 75 ? THEME.colors.info : progress >= 50 ? THEME.colors.warning : THEME.colors.danger) : null;

  return (
    <div
      style={{
        background: "var(--bg-card)", borderRadius: THEME.borderRadius.lg,
        padding: THEME.spacing.xl, boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)",
        border: "1px solid var(--border-color)", display: "flex", flexDirection: "column", gap: THEME.spacing.md,
        transition: "all 0.2s ease", cursor: "pointer"
      }}
      onMouseEnter={(e) => { e.currentTarget.style.transform = "translateY(-2px)"; e.currentTarget.style.boxShadow = "0 8px 16px rgba(0, 0, 0, 0.1)"; }}
      onMouseLeave={(e) => { e.currentTarget.style.transform = "translateY(0)"; e.currentTarget.style.boxShadow = "0 2px 8px rgba(0, 0, 0, 0.06)"; }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ width: "48px", height: "48px", borderRadius: THEME.borderRadius.lg, background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <Icon size={24} color={color} />
        </div>
        {status && (
          <span style={{ padding: "4px 10px", borderRadius: "12px", fontSize: "11px", fontWeight: "600", background: `${statusColor}15`, color: statusColor }}>
            {status}
          </span>
        )}
      </div>

      <div>
        <p style={{ fontSize: "13px", color: THEME.colors.text.secondary, margin: "0 0 6px 0", fontWeight: "500" }}>{label}</p>
        <p style={{ fontSize: "28px", fontWeight: "700", color: THEME.colors.text.primary, margin: 0, letterSpacing: "-0.5px" }}>{value}</p>
      </div>

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "4px", padding: "6px 12px", borderRadius: "20px", background: isUp ? "var(--success-soft)" : "var(--danger-soft)", color: isUp ? THEME.colors.success : THEME.colors.danger, fontSize: "12px", fontWeight: "600" }}>
          {isUp ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}
          {Math.abs(delta).toFixed(1)}%
        </div>
        {previousValue && (
          <span style={{ fontSize: "11px", color: THEME.colors.text.muted }}>vs {previousValue}</span>
        )}
      </div>

      {progress !== null && (
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "4px", fontSize: "11px", color: THEME.colors.text.muted }}>
            <span>Progress</span>
            <span>{progress.toFixed(0)}%</span>
          </div>
          <div style={{ height: "4px", background: "var(--hover-bg)", borderRadius: "2px", overflow: "hidden" }}>
            <div style={{ height: "100%", width: `${progress}%`, background: color, borderRadius: "2px", transition: "width 0.3s ease" }} />
          </div>
        </div>
      )}
    </div>
  );
}

/* ─── AI Recommendations Component ───────────────────────────────── */
function AIRecommendations({ metrics, timeRange }) {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);

  const generateRecommendations = async () => {
    setLoading(true);
    setTimeout(() => {
      const recs = [];
      
      if (metrics.conversion_rate < 2) {
        recs.push({
          type: "conversion",
          priority: "high",
          title: "Optimize conversion funnel",
          description: "Conversion rate is below 2%. Consider A/B testing landing pages and improving CTAs.",
          impact: "+15-25% conversion"
        });
      }
      
      if (metrics.growth_rate < 5) {
        recs.push({
          type: "growth",
          priority: "high",
          title: "Accelerate user acquisition",
          description: "Growth rate is slowing. Launch targeted campaigns and referral programs.",
          impact: "+10-20% growth"
        });
      }
      
      if (metrics.active_users < 100) {
        recs.push({
          type: "engagement",
          priority: "medium",
          title: "Boost user engagement",
          description: "Active users are low. Implement push notifications and email campaigns.",
          impact: "+30% engagement"
        });
      }
      
      if (metrics.total_revenue < 50000) {
        recs.push({
          type: "revenue",
          priority: "high",
          title: "Increase revenue streams",
          description: "Revenue is below target. Consider upselling, cross-selling, or premium features.",
          impact: "+20-40% revenue"
        });
      }

      if (recs.length === 0) {
        recs.push({
          type: "maintenance",
          priority: "low",
          title: "Maintain current performance",
          description: "All metrics are healthy. Focus on optimization and scaling.",
          impact: "Stable growth"
        });
      }

      setRecommendations(recs);
      setLoading(false);
    }, 800);
  };

  useEffect(() => {
    generateRecommendations();
  }, [metrics, timeRange]);

  const getPriorityColor = (priority) => {
    switch (priority) {
      case "high": return THEME.colors.danger;
      case "medium": return THEME.colors.warning;
      case "low": return THEME.colors.success;
      default: return THEME.colors.text.muted;
    }
  };

  const getTypeIcon = (type) => {
    switch (type) {
      case "conversion": return Target;
      case "growth": return TrendingUp;
      case "engagement": return Users;
      case "revenue": return DollarSign;
      default: return Lightbulb;
    }
  };

  return (
    <div style={{
      background: "var(--bg-card)", borderRadius: THEME.borderRadius.lg,
      padding: THEME.spacing.xl, border: "1px solid var(--border-color)",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)"
    }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: THEME.spacing.lg }}>
        <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.md }}>
          <div style={{
            width: "40px", height: "40px", borderRadius: THEME.borderRadius.md,
            background: `${THEME.colors.pink}15`, display: "flex", alignItems: "center", justifyContent: "center"
          }}>
            <Lightbulb size={20} color={THEME.colors.pink} />
          </div>
          <div>
            <h3 style={{ fontSize: "16px", fontWeight: "600", color: THEME.colors.text.primary, margin: 0 }}>AI Recommendations</h3>
            <p style={{ fontSize: "12px", color: THEME.colors.text.muted, margin: 0 }}>Actionable insights</p>
          </div>
        </div>
        <button
          onClick={generateRecommendations}
          disabled={loading}
          style={{ padding: "6px 12px", borderRadius: THEME.borderRadius.md, border: "1px solid var(--border-color)", background: "var(--hover-bg)", color: THEME.colors.text.secondary, fontSize: "12px", fontWeight: "500", cursor: loading ? "not-allowed" : "pointer", opacity: loading ? 0.5 : 1 }}
        >
          {loading ? <Loader2 size={12} style={{ animation: "spin 1s linear infinite" }} /> : <RefreshCw size={12} />}
        </button>
      </div>

      {loading ? (
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", padding: "20px" }}>
          <Loader2 size={24} style={{ animation: "spin 1s linear infinite", color: THEME.colors.text.muted }} />
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: THEME.spacing.md }}>
          {recommendations.map((rec, i) => {
            const Icon = getTypeIcon(rec.type);
            return (
              <div
                key={i}
                style={{
                  padding: THEME.spacing.md, borderRadius: THEME.borderRadius.md,
                  background: "var(--hover-bg)", border: "1px solid var(--border-color)",
                  display: "flex", gap: THEME.spacing.md, transition: "all 0.2s ease"
                }}
                onMouseEnter={(e) => e.currentTarget.style.borderColor = THEME.colors.primary}
                onMouseLeave={(e) => e.currentTarget.style.borderColor = "var(--border-color)"}
              >
                <div style={{
                  width: "36px", height: "36px", borderRadius: THEME.borderRadius.sm,
                  background: `${THEME.colors.primary}15`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0
                }}>
                  <Icon size={18} color={THEME.colors.primary} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.sm, marginBottom: "4px" }}>
                    <span style={{ fontSize: "14px", fontWeight: "600", color: THEME.colors.text.primary }}>{rec.title}</span>
                    <span style={{ fontSize: "10px", fontWeight: "600", padding: "2px 8px", borderRadius: "10px", background: `${getPriorityColor(rec.priority)}15`, color: getPriorityColor(rec.priority), textTransform: "uppercase" }}>{rec.priority}</span>
                  </div>
                  <p style={{ fontSize: "12px", color: THEME.colors.text.secondary, margin: "0 0 6px 0" }}>{rec.description}</p>
                  <span style={{ fontSize: "11px", fontWeight: "600", color: THEME.colors.success }}>{rec.impact}</span>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

/* ─── Real-Time Activity Feed Component ─────────────────────────── */
function ActivityFeed() {
  const [activities, setActivities] = useState([
    { id: 1, type: "registration", message: "New user registered", time: "2 min ago", icon: Users, color: THEME.colors.users },
    { id: 2, type: "conversion", message: "Deal closed - ₱25,000", time: "5 min ago", icon: DollarSign, color: THEME.colors.revenue },
    { id: 3, type: "campaign", message: "Email campaign sent", time: "15 min ago", icon: Megaphone, color: THEME.colors.purple },
    { id: 4, type: "system", message: "System health check passed", time: "30 min ago", icon: ShieldCheck, color: THEME.colors.success },
    { id: 5, type: "engagement", message: "User completed onboarding", time: "45 min ago", icon: Activity, color: THEME.colors.conversion },
  ]);

  return (
    <div style={{
      background: "var(--bg-card)", borderRadius: THEME.borderRadius.lg,
      padding: THEME.spacing.xl, border: "1px solid var(--border-color)",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.06)"
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.md, marginBottom: THEME.spacing.lg }}>
        <div style={{
          width: "40px", height: "40px", borderRadius: THEME.borderRadius.md,
          background: `${THEME.colors.info}15`, display: "flex", alignItems: "center", justifyContent: "center"
        }}>
          <Activity size={20} color={THEME.colors.info} />
        </div>
        <div>
          <h3 style={{ fontSize: "16px", fontWeight: "600", color: THEME.colors.text.primary, margin: 0 }}>Live Activity</h3>
          <p style={{ fontSize: "12px", color: THEME.colors.text.muted, margin: 0 }}>Real-time events</p>
        </div>
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: "4px" }}>
          <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: THEME.colors.success, animation: "pulse 2s infinite" }} />
          <span style={{ fontSize: "11px", color: THEME.colors.success, fontWeight: "500" }}>Live</span>
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: THEME.spacing.sm }}>
        {activities.map((activity) => {
          const Icon = activity.icon;
          return (
            <div
              key={activity.id}
              style={{
                display: "flex", alignItems: "center", gap: THEME.spacing.md,
                padding: THEME.spacing.sm, borderRadius: THEME.borderRadius.sm,
                transition: "background 0.2s ease"
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = "var(--hover-bg)"}
              onMouseLeave={(e) => e.currentTarget.style.background = "transparent"}
            >
              <div style={{
                width: "32px", height: "32px", borderRadius: THEME.borderRadius.sm,
                background: `${activity.color}15`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0
              }}>
                <Icon size={16} color={activity.color} />
              </div>
              <div style={{ flex: 1 }}>
                <p style={{ fontSize: "13px", color: THEME.colors.text.primary, margin: 0 }}>{activity.message}</p>
                <p style={{ fontSize: "11px", color: THEME.colors.text.muted, margin: 0 }}>{activity.time}</p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

/* ─── Helpers ────────────────────────────────────────────────── */
const fmt = (n) =>
  n >= 1_000_000 ? `₱${(n / 1_000_000).toFixed(1)}M`
    : n >= 1_000 ? `₱${(n / 1_000).toFixed(0)}k`
      : `₱${n}`;
const pctFmt = (n) => `${Number(n).toFixed(1)}%`;
const numFmt = (n) => Number(n).toLocaleString();
const calcChange = (arr) => {
  if (!arr || arr.length < 2) return 0;
  const latest = arr.at(-1)?.value ?? 0;
  const previous = arr.at(-2)?.value ?? 0;
  if (!previous) return 0;
  return ((latest - previous) / previous) * 100;
};
const buildFallbackTrend = (days, currentValue, baseline = 0) => {
  const safeCurrent = Number(currentValue) || baseline;
  return Array.from({ length: days }, (_, index) => {
    const d = new Date();
    d.setDate(d.getDate() - (days - index - 1));
    const progress = days <= 1 ? 1 : index / (days - 1);
    const value = safeCurrent > 0 ? Math.max(0, safeCurrent * (0.75 + progress * 0.25)) : 0;
    return { date: d.toLocaleDateString("en-CA"), value };
  });
};

/* ─── KPI Card ───────────────────────────────────────────────── */
function KpiCard({ label, value, delta, icon: Icon, color }) {
  const isUp = delta >= 0;
  return (
    <div
      style={{ background: "var(--bg-card)", borderRadius: "16px", padding: "24px", boxShadow: "0 1px 3px 0 rgb(0 0 0 / 0.1)", border: "1px solid var(--border-color)", display: "flex", flexDirection: "column", gap: "12px", transition: "all 0.2s ease", cursor: "pointer" }}
      onMouseEnter={(e) => { e.currentTarget.style.transform = "translateY(-2px)"; e.currentTarget.style.boxShadow = "0 10px 15px -3px rgb(0 0 0 / 0.1)"; }}
      onMouseLeave={(e) => { e.currentTarget.style.transform = "translateY(0)"; e.currentTarget.style.boxShadow = "0 1px 3px 0 rgb(0 0 0 / 0.1)"; }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ width: "48px", height: "48px", borderRadius: "12px", background: `${color}15`, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <Icon size={24} color={color} />
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: "4px", padding: "6px 12px", borderRadius: "20px", background: isUp ? "var(--success-soft)" : "var(--danger-soft)", color: isUp ? "var(--success)" : "var(--danger)", fontSize: "13px", fontWeight: "600" }}>
          {isUp ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}
          {Math.abs(delta).toFixed(1)}%
        </div>
      </div>
      <div>
        <p style={{ fontSize: "14px", color: "var(--text-secondary)", margin: "0 0 8px 0", fontWeight: "500" }}>{label}</p>
        <p style={{ fontSize: "28px", fontWeight: "700", color: "var(--text-primary)", margin: 0, letterSpacing: "-0.5px" }}>{value}</p>
      </div>
    </div>
  );
}

/* ─── Chart Card ─────────────────────────────────────────────── */
function ChartCard({ title, subtitle, children }) {
  return (
    <div style={{ background: "var(--bg-card)", borderRadius: "16px", padding: "24px", boxShadow: "0 1px 3px 0 rgb(0 0 0 / 0.1)", border: "1px solid var(--border-color)", display: "flex", flexDirection: "column", gap: "20px" }}>
      <div>
        <h3 style={{ fontSize: "16px", fontWeight: "600", color: "var(--text-primary)", margin: "0 0 4px 0" }}>{title}</h3>
        {subtitle && <p style={{ fontSize: "13px", color: "var(--text-muted)", margin: 0 }}>{subtitle}</p>}
      </div>
      {children}
    </div>
  );
}

/* ─── AI Insights Panel ──────────────────────────────────────── */
function AiInsightsPanel({ metrics, revenueChart, conversionChart, userChart, growthChart, timeRange }) {
  const [messages, setMessages] = useState([
    {
      role: "assistant",
      text: "Hello! I'm your analytics AI. I have full visibility into your current metrics. Ask me anything — trends, predictions, or recommendations.",
      chips: ["⚡ Real-time data connected", "📊 Predictive mode ready"],
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [predicting, setPredicting] = useState(false);
  const [predictions, setPredictions] = useState(null);
  const scrollRef = useRef(null);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, loading]);

  const buildContext = useCallback(() => {
    const revenueLatest = revenueChart.at(-1)?.value ?? metrics.total_revenue;
    const convLatest = conversionChart.at(-1)?.value ?? metrics.conversion_rate;
    const revenueArr = revenueChart.map((d) => `${d.date}: ₱${d.value.toFixed(0)}`).join(", ");
    const convArr = conversionChart.map((d) => `${d.date}: ${d.value.toFixed(2)}%`).join(", ");
    return `You are an expert business analytics AI assistant embedded in an admin analytics dashboard for a Philippine e-commerce/business platform.

LIVE METRICS (${timeRange} window):
- Total Revenue: ₱${revenueLatest.toLocaleString()}
- Active Users: ${metrics.active_users.toLocaleString()}
- Conversion Rate: ${convLatest.toFixed(2)}%
- Growth Rate: ${metrics.growth_rate.toFixed(2)}%

REVENUE TREND DATA: ${revenueArr || "Insufficient data"}
CONVERSION TREND DATA: ${convArr || "Insufficient data"}

TRAFFIC SOURCES: Direct 40%, Organic 30%, Referral 20%, Social 10%

INSTRUCTIONS:
- Give concise, actionable insights (under 120 words)
- Reference specific numbers from the data when relevant
- Use bullet points for lists (max 4 bullets)
- For predictions, state a confidence level
- Currency is Philippine Peso (₱)`;
  }, [metrics, revenueChart, conversionChart, timeRange]);

  const sendMessage = async (text) => {
    const msg = (text || input).trim();
    if (!msg || loading) return;
    setInput("");
    setMessages((prev) => [...prev, { role: "user", text: msg }]);
    setLoading(true);
    try {
      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${import.meta.env.VITE_GROQ_API_KEY}`,
        },
        body: JSON.stringify({
          model: "openai/gpt-oss-20b",
          max_tokens: 1000,
          messages: [
            { role: "system", content: buildContext() },
            { role: "user", content: msg }
          ],
        }),
      });
      if (!response.ok) throw new Error(`API error: ${response.status}`);
      const data = await response.json();
      const reply = data.choices?.[0]?.message?.content || "Unable to generate a response.";
      setMessages((prev) => [...prev, { role: "assistant", text: reply }]);
    } catch (err) {
      setMessages((prev) => [...prev, { role: "assistant", text: "⚠ Could not reach the AI service. Please try again shortly.", isError: true }]);
    } finally {
      setLoading(false);
    }
  };

  const calculateTrend = (data) => {
    if (!data || data.length < 2) return { slope: 0, r2: 0, avg: 0 };
    const n = data.length;
    const x = data.map((_, i) => i);
    const y = data.map((d) => d.value);
    const sx = x.reduce((a, b) => a + b, 0);
    const sy = y.reduce((a, b) => a + b, 0);
    const sxy = x.reduce((t, xi, i) => t + xi * y[i], 0);
    const sx2 = x.reduce((t, xi) => t + xi * xi, 0);
    const slope = (n * sxy - sx * sy) / (n * sx2 - sx * sx);
    const intercept = (sy - slope * sx) / n;
    const yMean = sy / n;
    const ssTotal = y.reduce((t, yi) => t + (yi - yMean) ** 2, 0);
    const ssRes = y.reduce((t, yi, i) => t + (yi - (slope * x[i] + intercept)) ** 2, 0);
    return { slope, r2: ssTotal > 0 ? 1 - ssRes / ssTotal : 0, avg: yMean };
  };

  const runPredictiveAnalysis = async () => {
    setPredicting(true);
    setPredictions(null);
    await new Promise((r) => setTimeout(r, 1500));
    try {
      const rT = calculateTrend(revenueChart);
      const cT = calculateTrend(conversionChart);
      const uT = calculateTrend(userChart);
      const D = 30;
      const pR = rT.avg + rT.slope * D;
      const pC = cT.avg + cT.slope * D;
      const pU = uT.avg + uT.slope * D;
      const curR = revenueChart.at(-1)?.value || rT.avg || 1;
      const curC = conversionChart.at(-1)?.value || cT.avg || 1;
      const curU = userChart.at(-1)?.value || uT.avg || 1;
      const pts = revenueChart.length || 1;
      const confidence = Math.round(60 + Math.min(25, ((rT.r2 + cT.r2) / 2) * 25) + Math.min(15, (pts / 30) * 15));
      let topRisk = "Insufficient data for risk analysis";
      let topOpportunity = "Insufficient data for opportunity analysis";
      if (cT.slope < 0) topRisk = "Conversion rate trending downward";
      else if (rT.slope < 0) topRisk = "Revenue growth slowing";
      else if (confidence < 70) topRisk = "Low prediction confidence — collect more data";
      if (cT.slope > 0 && rT.slope > 0) topOpportunity = "Strong conversion + revenue growth trajectory";
      else if (uT.slope > 0) topOpportunity = "User acquisition accelerating";
      else if (rT.slope > uT.slope && uT.slope > 0) topOpportunity = "Revenue per user increasing";
      setPredictions({
        projectedRevenue: { value: Math.max(0, pR), change: ((pR - curR) / curR) * 100, confidence },
        projectedUsers: { value: Math.max(0, Math.round(pU)), change: ((pU - curU) / curU) * 100, confidence: Math.round(confidence * 0.9) },
        projectedConversion: { value: Math.max(0, Math.min(100, pC)), change: ((pC - curC) / curC) * 100, confidence: Math.round(confidence * 0.85) },
        topRisk, topOpportunity,
      });
    } catch {
      setPredictions({ error: "Failed to generate predictions" });
    } finally {
      setPredicting(false);
    }
  };

  const ttStyle = { backgroundColor: "var(--bg-card)", border: "1px solid var(--border-color)", borderRadius: "8px", boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)", fontSize: "12px", padding: "8px 12px" };

  return (
    <div style={{ background: "var(--bg-card)", borderRadius: "16px", boxShadow: "0 1px 3px 0 rgb(0 0 0 / 0.1)", border: "1px solid var(--border-color)", display: "flex", flexDirection: "column", height: "100%", overflow: "hidden" }}>
      {/* Header */}
      <div style={{ padding: "20px 24px", borderBottom: `1px solid ${THEME.colors.border}`, display: "flex", alignItems: "center", justifyContent: "space-between", background: "linear-gradient(135deg, var(--brand-cyan-soft), var(--brand-gold-soft))" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <div style={{ width: "36px", height: "36px", borderRadius: "10px", background: "rgba(255,255,255,0.2)", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Sparkles size={20} color="white" />
          </div>
          <div>
            <h3 style={{ fontSize: "16px", fontWeight: "600", color: "white", margin: 0 }}>AI Insights</h3>
            <p style={{ fontSize: "12px", color: "rgba(255,255,255,0.8)", margin: 0 }}>Powered by Claude</p>
          </div>
        </div>
        <button onClick={runPredictiveAnalysis} disabled={predicting} style={{ display: "flex", alignItems: "center", gap: "6px", padding: "8px 16px", borderRadius: "8px", border: "none", background: "rgba(255,255,255,0.2)", color: "white", fontSize: "13px", fontWeight: "500", cursor: predicting ? "not-allowed" : "pointer", opacity: predicting ? 0.7 : 1 }}>
          {predicting ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <Brain size={14} />}
          {predicting ? "Analyzing..." : "Forecast"}
        </button>
      </div>

      {/* Predictions */}
      {predictions && !predictions.error && (
        <div style={{ padding: "16px 20px", background: "var(--hover-bg)", borderBottom: `1px solid ${THEME.colors.border}` }}>
          <p style={{ fontSize: "12px", fontWeight: "600", color: "var(--text-secondary)", margin: "0 0 12px 0", textTransform: "uppercase", letterSpacing: "0.5px" }}>30-Day Forecast</p>
          <div style={{ display: "flex", gap: "12px" }}>
            {[
              { label: "Revenue", value: fmt(predictions.projectedRevenue.value), change: predictions.projectedRevenue.change, conf: predictions.projectedRevenue.confidence, color: THEME.colors.revenue },
              { label: "Users", value: numFmt(predictions.projectedUsers.value), change: predictions.projectedUsers.change, conf: predictions.projectedUsers.confidence, color: THEME.colors.users },
              { label: "Conv.", value: pctFmt(predictions.projectedConversion.value), change: predictions.projectedConversion.change, conf: predictions.projectedConversion.confidence, color: THEME.colors.conversion },
            ].map((pred, i) => (
              <div key={i} style={{ flex: 1, padding: "12px", background: "var(--bg-card)", borderRadius: "10px", border: "1px solid var(--border-color)" }}>
                <p style={{ fontSize: "11px", color: "var(--text-muted)", margin: "0 0 6px 0" }}>{pred.label}</p>
                <p style={{ fontSize: "16px", fontWeight: "700", color: "var(--text-primary)", margin: "0 0 4px 0" }}>{pred.value}</p>
                <div style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                  <span style={{ fontSize: "11px", color: pred.change >= 0 ? THEME.colors.success : THEME.colors.danger, fontWeight: "600" }}>
                    {pred.change >= 0 ? "+" : ""}{pred.change.toFixed(1)}%
                  </span>
                  <div style={{ flex: 1, height: "4px", background: THEME.colors.border, borderRadius: "2px", overflow: "hidden" }}>
                    <div style={{ width: `${pred.conf}%`, height: "100%", background: pred.color, borderRadius: "2px" }} />
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginTop: "12px" }}>
            <div style={{ padding: "10px 12px", background: "var(--danger-soft)", borderRadius: "8px" }}>
              <p style={{ fontSize: "10px", fontWeight: "600", color: "var(--danger)", margin: "0 0 4px 0", textTransform: "uppercase" }}>Top Risk</p>
              <p style={{ fontSize: "12px", color: "#7f1d1d", margin: 0 }}>{predictions.topRisk}</p>
            </div>
            <div style={{ padding: "10px 12px", background: "var(--success-soft)", borderRadius: "8px" }}>
              <p style={{ fontSize: "10px", fontWeight: "600", color: "var(--success)", margin: "0 0 4px 0", textTransform: "uppercase" }}>Opportunity</p>
              <p style={{ fontSize: "12px", color: "#14532d", margin: 0 }}>{predictions.topOpportunity}</p>
            </div>
          </div>
        </div>
      )}

      {/* Messages */}
      <div ref={scrollRef} style={{ flex: 1, overflow: "auto", padding: "20px", display: "flex", flexDirection: "column", gap: "16px" }}>
        {messages.map((msg, i) => (
          <div key={i} style={{ display: "flex", gap: "12px", alignSelf: msg.role === "user" ? "flex-end" : "flex-start", maxWidth: "85%" }}>
            {msg.role === "assistant" && (
              <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: "linear-gradient(135deg, var(--brand-cyan), var(--brand-gold))", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <Sparkles size={16} color="white" />
              </div>
            )}
            <div>
              <div style={{ padding: "12px 16px", borderRadius: "12px", background: msg.role === "user" ? "var(--brand-cyan)" : msg.isError ? "var(--danger-soft)" : "var(--hover-bg)", color: msg.role === "user" ? "white" : msg.isError ? "var(--danger)" : "var(--text-primary)", fontSize: "14px", lineHeight: "1.6", whiteSpace: "pre-wrap" }}>
                {msg.text}
              </div>
              {msg.chips && (
                <div style={{ display: "flex", gap: "6px", marginTop: "8px" }}>
                  {msg.chips.map((chip, ci) => (
                    <span key={ci} style={{ padding: "4px 10px", borderRadius: "12px", background: "var(--brand-cyan-soft)", color: "var(--brand-cyan)", fontSize: "11px", fontWeight: "500" }}>{chip}</span>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
        {loading && (
          <div style={{ display: "flex", gap: "12px", alignSelf: "flex-start" }}>
            <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: "linear-gradient(135deg, var(--brand-cyan), var(--brand-gold))", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <Sparkles size={16} color="white" />
            </div>
            <div style={{ padding: "12px 16px", borderRadius: "12px", background: "var(--hover-bg)", display: "flex", gap: "4px", alignItems: "center" }}>
              {[0, 0.2, 0.4].map((delay, i) => (
                <span key={i} style={{ width: "8px", height: "8px", borderRadius: "50%", background: THEME.colors.text.muted, animation: `bounce 1s infinite ${delay}s` }} />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Quick Prompts */}
      <div style={{ padding: "12px 20px", borderTop: `1px solid ${THEME.colors.border}`, display: "flex", gap: "8px", overflowX: "auto" }}>
        {QUICK_PROMPTS.map((prompt, i) => (
          <button key={i} onClick={() => sendMessage(prompt)} disabled={loading} style={{ padding: "8px 14px", borderRadius: "20px", border: "1px solid var(--border-color)", background: "var(--bg-card)", color: "var(--text-secondary)", fontSize: "12px", whiteSpace: "nowrap", cursor: loading ? "not-allowed" : "pointer", opacity: loading ? 0.6 : 1 }}>
            {prompt}
          </button>
        ))}
      </div>

      {/* Input */}
      <div style={{ padding: "16px 20px", borderTop: `1px solid ${THEME.colors.border}`, display: "flex", gap: "12px" }}>
        <input
          type="text" value={input} onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && !loading && sendMessage()}
          placeholder="Ask about your analytics..." disabled={loading}
          style={{ flex: 1, padding: "12px 16px", borderRadius: "10px", border: "1px solid var(--border-color)", fontSize: "14px", outline: "none", background: "var(--bg-card)" }}
        />
        <button onClick={() => sendMessage()} disabled={loading || !input.trim()}
          style={{ width: "44px", height: "44px", borderRadius: "10px", border: "none", background: THEME.colors.primary, color: "white", display: "flex", alignItems: "center", justifyContent: "center", cursor: loading || !input.trim() ? "not-allowed" : "pointer", opacity: loading || !input.trim() ? 0.6 : 1 }}>
          <Send size={18} />
        </button>
      </div>
    </div>
  );
}

/* ─── User Table with Pagination, Search & Filters ───────────── */
function UserTable({ userList, loading }) {
  const [page, setPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [roleFilter, setRoleFilter] = useState("all");

  useEffect(() => setPage(1), [userList.length, searchQuery, roleFilter]);

  // Filter users based on search and role
  const filteredUsers = useMemo(() => {
    return userList.filter((user) => {
      const matchesSearch =
        !searchQuery ||
        (user.full_name || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
        (user.email || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
        (user.role || "Client").toLowerCase().includes(searchQuery.toLowerCase());

      const matchesRole =
        roleFilter === "all" ||
        (user.role || "Client").toLowerCase() === roleFilter.toLowerCase();

      return matchesSearch && matchesRole;
    });
  }, [userList, searchQuery, roleFilter]);

  const totalPages = Math.ceil(filteredUsers.length / PAGE_SIZE);
  const pageSlice = filteredUsers.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  // Get unique roles for filter dropdown
  const availableRoles = useMemo(() => {
    const roles = new Set(userList.map((u) => u.role || "Client"));
    return Array.from(roles).sort();
  }, [userList]);

  // Helper: get initials from full_name or email
  const getInitial = (user) =>
    (user.full_name?.[0] || user.email?.[0] || "?").toUpperCase();

  // Helper: derive display username from email
  const getUsername = (user) =>
    user.email ? `@${user.email.split("@")[0]}` : "";

  // Role badge colours — handles capitalised ("Admin") and lowercase ("admin")
  const getRoleBadge = (role) => {
    const r = (role || "Client").toLowerCase();
    if (r === "admin") return { bg: "#fef3c7", color: "#92400e" };
    return { bg: "var(--brand-cyan-soft)", color: "var(--brand-cyan)" };
  };

  // Clear all filters
  const clearFilters = () => {
    setSearchQuery("");
    setRoleFilter("all");
    setPage(1);
  };

  const hasActiveFilters = searchQuery || roleFilter !== "all";

  return (
    <div style={{ marginTop: "24px" }}>
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "16px", flexWrap: "wrap", gap: "12px" }}>
        <h3 style={{ fontSize: "16px", fontWeight: "600", color: "var(--text-primary)", margin: 0 }}>
          All Users
        </h3>
        <span style={{ fontSize: "13px", color: "var(--text-muted)" }}>
          {filteredUsers.length.toLocaleString()} shown
          {hasActiveFilters && ` of ${userList.length.toLocaleString()} total`}
          {totalPages > 1 && ` · page ${page} of ${totalPages}`}
        </span>
      </div>

      {/* Search & Filters Bar */}
      <div style={{ display: "flex", gap: "12px", marginBottom: "16px", flexWrap: "wrap", alignItems: "center" }}>
        {/* Search Input */}
        <div style={{ position: "relative", flex: "1", minWidth: "200px", maxWidth: "400px" }}>
          <Search size={16} style={{ position: "absolute", left: "12px", top: "50%", transform: "translateY(-50%)", color: "#000" }} />
          <input
            type="text"
            placeholder="Search by name, email, or role..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{
              width: "100%",
              padding: "10px 12px 10px 40px",
              borderRadius: "10px",
              border: "1px solid var(--border-color)",
              fontSize: "14px",
              outline: "none",
              background: "var(--bg-card)",
              color: "#000", 
              transition: "border-color 0.2s",
            }}
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery("")}
              style={{
                position: "absolute",
                right: "8px",
                top: "50%",
                transform: "translateY(-50%)",
                background: "none",
                border: "none",
                cursor: "pointer",
                padding: "4px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "var(--text-muted)",
              }}
            >
              <X size={14} />
            </button>
          )}
        </div>

        {/* Role Filter */}
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <Filter size={16} color={THEME.colors.text.secondary} />
          <select
            value={roleFilter}
            onChange={(e) => setRoleFilter(e.target.value)}
            style={{
              padding: "10px 14px",
              borderRadius: "10px",
              border: "1px solid var(--border-color)",
              fontSize: "14px",
              background: "var(--bg-card)",
              cursor: "pointer",
              outline: "none",
              minWidth: "120px",
              color: "#000",
            }}
          >
            <option value="all">All Roles</option>
            {availableRoles.map((role) => (
              <option key={role} value={role}>
                {role}
              </option>
            ))}
          </select>
        </div>

        {/* Clear Filters */}
        {hasActiveFilters && (
          <button
            onClick={clearFilters}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "6px",
              padding: "10px 14px",
              borderRadius: "10px",
              border: "1px solid var(--border-color)",
              background: "var(--bg-card)",
              color: "var(--text-secondary)",
              fontSize: "13px",
              cursor: "pointer",
              transition: "all 0.2s",
            }}
          >
            <X size={14} />
            Clear
          </button>
        )}
      </div>

      <div style={{ background: "var(--bg-card)", borderRadius: "16px", border: "1px solid var(--border-color)", overflow: "hidden" }}>
        {loading ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--text-muted)" }}>
            <Loader2 size={24} style={{ animation: "spin 1s linear infinite", marginBottom: "12px" }} />
            <p>Loading all users…</p>
          </div>
        ) : userList.length === 0 ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--text-muted)" }}>
            <Users size={32} style={{ marginBottom: "12px", opacity: 0.5 }} />
            <p>No users found</p>
          </div>
        ) : filteredUsers.length === 0 ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--text-muted)" }}>
            <Search size={32} style={{ marginBottom: "12px", opacity: 0.5 }} />
            <p style={{ margin: "0 0 8px 0" }}>No users match your filters</p>
            <button
              onClick={clearFilters}
              style={{
                padding: "8px 16px",
                borderRadius: "8px",
                border: "1px solid var(--border-color)",
                background: "var(--bg-card)",
                color: THEME.colors.primary,
                fontSize: "13px",
                cursor: "pointer",
              }}
            >
              Clear Filters
            </button>
          </div>
        ) : (
          <>
            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr style={{ background: "var(--hover-bg)", borderBottom: `1px solid ${THEME.colors.border}` }}>
                    {["#", "User", "Email", "Role", "Joined"].map((col) => (
                      <th key={col} style={{ padding: "14px 16px", textAlign: "left", fontSize: "12px", fontWeight: "600", color: "var(--text-secondary)", textTransform: "uppercase", letterSpacing: "0.5px", whiteSpace: "nowrap" }}>
                        {col}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {pageSlice.map((user, idx) => {
                    const rowNum = (page - 1) * PAGE_SIZE + idx + 1;
                    const badge = getRoleBadge(user.role);
                    return (
                      <tr
                        key={user.id}
                        style={{ borderBottom: idx < pageSlice.length - 1 ? `1px solid ${THEME.colors.border}` : "none", transition: "background 0.15s" }}
                        onMouseEnter={(e) => (e.currentTarget.style.background = "var(--hover-bg)")} 
                        onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
                      >
                        {/* Row number */}
                        <td style={{ padding: "14px 16px", fontSize: "12px", color: "var(--text-muted)", width: "40px" }}>
                          {rowNum}
                        </td>

                        {/* User — avatar + full_name + derived username */}
                        <td style={{ padding: "14px 16px" }}>
                          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                            <div style={{ width: "40px", height: "40px", borderRadius: "50%", background: user.avatar_url ? "transparent" : THEME.colors.primary, display: "flex", alignItems: "center", justifyContent: "center", overflow: "hidden", fontSize: "14px", fontWeight: "600", color: "white", flexShrink: 0 }}>
                              {user.avatar_url
                                ? <img src={user.avatar_url} alt="" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                                : getInitial(user)}
                            </div>
                            <div>
                              <p style={{ margin: 0, fontSize: "14px", fontWeight: "500", color: "var(--text-primary)" }}>
                                {user.full_name || "Unnamed User"}
                              </p>
                              <p style={{ margin: "2px 0 0 0", fontSize: "12px", color: "var(--text-muted)" }}>
                                {getUsername(user)}
                              </p>
                            </div>
                          </div>
                        </td>

                        {/* Email */}
                        <td style={{ padding: "14px 16px" }}>
                          <p style={{ margin: 0, fontSize: "13px", color: "var(--text-primary)" }}>
                            {user.email || "-"}
                          </p>
                        </td>

                        {/* Role — handles "Admin", "Client", etc. */}
                        <td style={{ padding: "14px 16px" }}>
                          <span style={{ padding: "4px 10px", borderRadius: "12px", fontSize: "12px", fontWeight: "500", background: badge.bg, color: badge.color }}>
                            {user.role || "Client"}
                          </span>
                        </td>

                        {/* Joined */}
                        <td style={{ padding: "14px 16px" }}>
                          <p style={{ margin: 0, fontSize: "13px", color: "var(--text-primary)" }}>
                            {new Date(user.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                          </p>
                          <p style={{ margin: "2px 0 0 0", fontSize: "12px", color: "var(--text-muted)" }}>
                            {new Date(user.created_at).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}
                          </p>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>

            {/* Pagination bar */}
            {totalPages > 1 && (
              <div style={{ padding: "14px 20px", borderTop: `1px solid ${THEME.colors.border}`, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <span style={{ fontSize: "13px", color: "var(--text-muted)" }}>
                  Showing {((page - 1) * PAGE_SIZE + 1).toLocaleString()}–{Math.min(page * PAGE_SIZE, filteredUsers.length).toLocaleString()} of {filteredUsers.length.toLocaleString()}
                </span>
                <div style={{ display: "flex", gap: "6px", alignItems: "center" }}>
                  <button
                    onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1}
                    style={{ width: "32px", height: "32px", borderRadius: "8px", border: "1px solid var(--border-color)", background: "var(--bg-card)", display: "flex", alignItems: "center", justifyContent: "center", cursor: page === 1 ? "not-allowed" : "pointer", opacity: page === 1 ? 0.4 : 1 }}>
                    <ChevronLeft size={16} />
                  </button>

                  {Array.from({ length: totalPages }, (_, i) => i + 1)
                    .filter((p) => p === 1 || p === totalPages || Math.abs(p - page) <= 2)
                    .reduce((acc, p, i, arr) => {
                      if (i > 0 && p - arr[i - 1] > 1) acc.push("…");
                      acc.push(p);
                      return acc;
                    }, [])
                    .map((item, i) =>
                      item === "…" ? (
                        <span key={`ellipsis-${i}`} style={{ fontSize: "13px", color: "var(--text-muted)", padding: "0 4px" }}>…</span>
                      ) : (
                        <button
                          key={item} onClick={() => setPage(item)}
                          style={{ width: "32px", height: "32px", borderRadius: "8px", border: `1px solid ${item === page ? THEME.colors.primary : THEME.colors.border}`, background: item === page ? THEME.colors.primary : "white", color: item === page ? "white" : THEME.colors.text.secondary, fontSize: "13px", fontWeight: item === page ? "600" : "400", cursor: "pointer" }}>
                          {item}
                        </button>
                      )
                    )}

                  <button
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages}
                    style={{ width: "32px", height: "32px", borderRadius: "8px", border: "1px solid var(--border-color)", background: "var(--bg-card)", display: "flex", alignItems: "center", justifyContent: "center", cursor: page === totalPages ? "not-allowed" : "pointer", opacity: page === totalPages ? 0.4 : 1 }}>
                    <ChevronRight size={16} />
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

/* ─── Main Component ─────────────────────────────────────────── */
export default function AdminAnalytics() {
  const [metrics, setMetrics] = useState({ total_revenue: 0, growth_rate: 0, active_users: 0, conversion_rate: 0 });
  const [metricsHistory, setMetricsHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [timeRange, setTimeRange] = useState("7d");
  const [customStartDate, setCustomStartDate] = useState("");
  const [customEndDate, setCustomEndDate] = useState("");
  const [showCustomPicker, setShowCustomPicker] = useState(false);
  const snapshotRef = useRef(null);

  const [userStats, setUserStats] = useState({
    totalUsers: 0, newUsersThisMonth: 0, userGrowthRate: 0,
    roleDistribution: [], statusDistribution: [], registrationTrend: [],
  });
  const [userList, setUserList] = useState([]);
  const [userTableLoading, setUserTableLoading] = useState(false);

  const rangeInDays = (r) => (r === "7d" ? 7 : r === "30d" ? 30 : 90);

  const filterByTimeRange = useCallback((data) => {
    if (timeRange === "custom" && customStartDate && customEndDate) {
      const start = new Date(customStartDate);
      const end = new Date(customEndDate);
      end.setHours(23, 59, 59, 999);
      return (data || []).filter((item) => {
        const date = new Date(item.recorded_at || item.created_at);
        return date >= start && date <= end;
      });
    }
    const now = new Date();
    const days = rangeInDays(timeRange);
    return (data || []).filter((item) => {
      const date = new Date(item.recorded_at || item.created_at);
      return (now - date) / (1000 * 60 * 60 * 24) <= days;
    });
  }, [timeRange, customStartDate, customEndDate]);

  const calcChange_ = (newVal, oldVal) => (!oldVal ? 0 : ((newVal - oldVal) / oldVal) * 100);

  const fetchActiveUsers = async (startDate) => {
    const { count, error } = await supabase.from("profiles").select("id", { count: "exact", head: true }).gte("updated_at", startDate.toISOString());
    if (error) throw error;
    return count ?? 0;
  };

  /* ── Fetch ALL users using Admin client (bypasses RLS) ── */
  const fetchAllUsers = async () => {
    setUserTableLoading(true);
    try {
      const { fetchAllProfilesAdmin } = await import("../../config/supabaseAdminClient.js");
      const { data, error } = await fetchAllProfilesAdmin();
      if (error) throw error;
      setUserList(data || []);
    } catch (err) {
      console.error("Error fetching all users:", err);
      // Fallback: try regular client
      try {
        const { data } = await supabase
          .from("profiles")
          .select("*")
          .order("created_at", { ascending: false })
          .limit(1000);
        setUserList(data || []);
      } catch (fallbackErr) {
        console.error("Fallback also failed:", fallbackErr);
      }
    } finally {
      setUserTableLoading(false);
    }
  };

  const fetchUserAnalytics = async () => {
    try {
      const { count: totalUsers } = await supabase.from("profiles").select("id", { count: "exact", head: true });

      const startOfMonth = new Date();
      startOfMonth.setDate(1); startOfMonth.setHours(0, 0, 0, 0);
      const { count: newUsersThisMonth } = await supabase.from("profiles").select("id", { count: "exact", head: true }).gte("created_at", startOfMonth.toISOString());

      const startOfLastMonth = new Date(startOfMonth);
      startOfLastMonth.setMonth(startOfLastMonth.getMonth() - 1);
      const { count: lastMonthUsers } = await supabase.from("profiles").select("id", { count: "exact", head: true }).gte("created_at", startOfLastMonth.toISOString()).lt("created_at", startOfMonth.toISOString());

      const userGrowthRate = lastMonthUsers > 0 ? ((newUsersThisMonth - lastMonthUsers) / lastMonthUsers) * 100 : 0;

      // Only select the columns that exist in this table
      const { data: users } = await supabase.from("profiles").select("role, created_at");

      const roleCounts = {}, registrationsByDate = {};
      users?.forEach((user) => {
        // Normalise role to capitalised form for display consistency
        const role = user.role || "Client";
        roleCounts[role] = (roleCounts[role] || 0) + 1;

        const userDate = new Date(user.created_at);
        const daysAgo = Math.floor((Date.now() - userDate.getTime()) / (1000 * 60 * 60 * 24));
        if (daysAgo <= 30) {
          const dateKey = userDate.toLocaleDateString("en-CA");
          registrationsByDate[dateKey] = (registrationsByDate[dateKey] || 0) + 1;
        }
      });

      const roleDistribution = Object.entries(roleCounts).map(([name, value]) => ({ name, value }));

      const registrationTrend = [];
      for (let i = 29; i >= 0; i--) {
        const d = new Date(); d.setDate(d.getDate() - i);
        const dateKey = d.toLocaleDateString("en-CA");
        registrationTrend.push({ date: dateKey, value: registrationsByDate[dateKey] || 0 });
      }

      setUserStats({
        totalUsers: totalUsers || 0,
        newUsersThisMonth: newUsersThisMonth || 0,
        userGrowthRate,
        roleDistribution,
        // No status column — derive from updated_at as a proxy (active if updated in last 30d)
        statusDistribution: [],
        registrationTrend,
      });
    } catch (err) { console.error("Error fetching user analytics:", err); }
  };

  const computeGrowthRate = async () => {
    if (timeRange === "custom" && customStartDate && customEndDate) {
      const start = new Date(customStartDate);
      const end = new Date(customEndDate);
      const daysDiff = Math.ceil((end - start) / (1000 * 60 * 60 * 24));
      const pStart = new Date(start);
      pStart.setDate(pStart.getDate() - daysDiff);
      const pEnd = new Date(start);
      const [current, previous] = await Promise.all([
        fetchActiveUsers(start),
        fetchActiveUsers(pStart)
      ]);
      return calcChange_(current, previous);
    }
    const now = new Date(), days = rangeInDays(timeRange);
    const cStart = new Date(); cStart.setDate(now.getDate() - days);
    const pStart = new Date(cStart); pStart.setDate(cStart.getDate() - days);
    const [current, previous] = await Promise.all([fetchActiveUsers(cStart), fetchActiveUsers(pStart)]);
    return calcChange_(current, previous);
  };

  const buildChartData = (data, metricName) => {
    const grouped = {};
    (data || []).filter((m) => m.metric_name === metricName).forEach((item) => {
      const date = new Date(item.recorded_at).toLocaleDateString("en-CA");
      if (!grouped[date]) grouped[date] = [];
      grouped[date].push(Number(item.value));
    });
    return Object.keys(grouped).sort().map((date) => ({ date, value: grouped[date].reduce((a, b) => a + b, 0) / grouped[date].length }));
  };

  const loadAnalyticsData = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase.from("metrics").select("*").order("recorded_at", { ascending: true });
      if (error) throw error;
      const filtered = filterByTimeRange(data);
      let activeUsersCount;
      if (timeRange === "custom" && customStartDate) {
        activeUsersCount = await fetchActiveUsers(new Date(customStartDate));
      } else {
        activeUsersCount = await fetchActiveUsers(new Date(Date.now() - rangeInDays(timeRange) * 86400000));
      }
      const growthRateValue = await computeGrowthRate();
      const revenue = buildChartData(filtered, "total_revenue");
      const conversion = buildChartData(filtered, "conversion_rate");
      const activeUsers = buildChartData(filtered, "active_users");
      const growth = buildChartData(filtered, "growth_rate");
      const fallbackDays = rangeInDays(timeRange);
      const fallbackHistory = [
        ...buildFallbackTrend(fallbackDays, revenue.at(-1)?.value ?? 0).map((item) => ({ metric_name: "total_revenue", recorded_at: item.date, value: item.value })),
        ...buildFallbackTrend(fallbackDays, activeUsers.at(-1)?.value ?? activeUsersCount).map((item) => ({ metric_name: "active_users", recorded_at: item.date, value: item.value })),
        ...buildFallbackTrend(fallbackDays, conversion.at(-1)?.value ?? 0).map((item) => ({ metric_name: "conversion_rate", recorded_at: item.date, value: item.value })),
        ...buildFallbackTrend(fallbackDays, growth.at(-1)?.value ?? growthRateValue).map((item) => ({ metric_name: "growth_rate", recorded_at: item.date, value: item.value })),
      ];
      setMetricsHistory(filtered);
      setMetricsHistory(filtered.length > 0 ? filtered : fallbackHistory);
      setMetrics({ total_revenue: revenue.at(-1)?.value ?? 0, active_users: activeUsersCount, conversion_rate: conversion.at(-1)?.value ?? 0, growth_rate: growthRateValue });
      await fetchUserAnalytics();
      await fetchAllUsers();
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  const revenueChart = useMemo(() => buildChartData(metricsHistory, "total_revenue"), [metricsHistory]);
  const userChart = useMemo(() => buildChartData(metricsHistory, "active_users"), [metricsHistory]);
  const conversionChart = useMemo(() => buildChartData(metricsHistory, "conversion_rate"), [metricsHistory]);
  const growthChart = useMemo(() => buildChartData(metricsHistory, "growth_rate"), [metricsHistory]);

  const revenueChange = calcChange(revenueChart);
  const userChange = calcChange(userChart);
  const conversionChange = calcChange(conversionChart);
  const growthChange = calcChange(growthChart);

  useEffect(() => {
    loadAnalyticsData();
    const interval = setInterval(loadAnalyticsData, 30000);
    return () => clearInterval(interval);
  }, [timeRange]);

  useEffect(() => {
    const channel = supabase
      .channel("metrics-live")
      .on("postgres_changes", { event: "*", schema: "public", table: "metrics" }, (payload) => {
        const row = payload.new;
        if (!row) return;
        setMetricsHistory((prev) => filterByTimeRange([...prev, row]));
      })
      .subscribe();
    return () => supabase.removeChannel(channel);
  }, [timeRange]);

  const exportXLSX = async () => {
    if (!metricsHistory?.length) return;

    try {
      const { default: ExcelJS } = await import('exceljs');
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet('Analytics Report');
      
      // Group data by date
      const grouped = {};
      metricsHistory.forEach((item) => {
        const date = new Date(item.recorded_at).toISOString().split("T")[0];
        if (!grouped[date]) grouped[date] = { date };
        const value = parseFloat(item.value) || 0;
        if (item.metric_name in grouped[date]) grouped[date][item.metric_name] += value;
        else grouped[date][item.metric_name] = value;
      });
      
      const exportData = Object.values(grouped).sort((a, b) => new Date(a.date) - new Date(b.date));
      
      // Add headers
      if (exportData.length > 0) {
        const headers = Object.keys(exportData[0]);
        worksheet.addRow(headers);
        
        // Style headers
        const headerRow = worksheet.getRow(1);
        headerRow.font = { bold: true, color: { argb: 'FFFFFF' } };
        headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF366094' } };
        headerRow.alignment = { horizontal: 'center' };
        
        // Add data
        exportData.forEach(row => {
          worksheet.addRow(Object.values(row));
        });
        
        // Auto-fit columns
        worksheet.columns.forEach((column, index) => {
          const maxLength = Math.max(
            headers[index]?.length || 0,
            ...exportData.map(row => String(row[headers[index]] || "").length)
          );
          column.width = Math.min(maxLength + 2, 50);
        });
      }
      
      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `analytics-report-${timeRange}-${new Date().toISOString().split("T")[0]}.xlsx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error exporting Excel file:', error);
    }
  };

  const exportPDF = async () => {
    if (!snapshotRef.current) return;
    const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
      import("jspdf"),
      import("html2canvas"),
    ]);
    const canvas = await html2canvas(snapshotRef.current);
    const img = canvas.toDataURL("image/png");
    const pdf = new jsPDF({ orientation: "landscape" });
    pdf.addImage(img, "PNG", 10, 10, 277, 0);
    pdf.save("analytics.pdf");
  };

  const tooltipStyle = { backgroundColor: "var(--bg-card)", border: "1px solid var(--border-color)", borderRadius: "8px", boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)", fontSize: "12px", padding: "8px 12px" };

  return (
    <div ref={snapshotRef} style={{ minHeight: "100vh", background: "transparent", padding: "24px" }}>
      <style>{`
        @keyframes spin   { from { transform: rotate(0deg); }   to { transform: rotate(360deg); } }
        @keyframes bounce { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-4px); } }
        @keyframes pulse  { 0%,100% { opacity: 1; } 50% { opacity: 0.5; } }
      `}</style>

      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: THEME.spacing.xl }}>
        <div>
          <h1 style={{ fontSize: "32px", fontWeight: "700", color: "var(--text-primary)", letterSpacing: "-0.5px" }}>Analytics Dashboard</h1>
          <p style={{ fontSize: "15px", color: "var(--text-secondary)", margin: "4px 0 0 0" }}>Enterprise-grade business intelligence & insights</p>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.lg }}>
          <div style={{ display: "flex", background: "var(--bg-card)", borderRadius: THEME.borderRadius.md, padding: "4px", border: "1px solid var(--border-color)" }}>
            {RANGES.map((r) => (
              <button
                key={r.key}
                onClick={() => {
                  setTimeRange(r.key);
                  if (r.key === "custom") {
                    setShowCustomPicker(true);
                  } else {
                    setShowCustomPicker(false);
                  }
                }}
                style={{ padding: "8px 16px", borderRadius: THEME.borderRadius.sm, border: "none", background: timeRange === r.key ? THEME.colors.primary : "transparent", color: timeRange === r.key ? "white" : THEME.colors.text.secondary, fontSize: "13px", fontWeight: "500", cursor: "pointer", transition: "all 0.2s" }}
              >
                {r.label}
              </button>
            ))}
          </div>
          {showCustomPicker && (
            <div style={{ display: "flex", alignItems: "center", gap: THEME.spacing.sm, background: "var(--bg-card)", borderRadius: THEME.borderRadius.md, padding: "8px 12px", border: "1px solid var(--border-color)" }}>
              <input
                type="date"
                value={customStartDate}
                onChange={(e) => setCustomStartDate(e.target.value)}
                style={{ padding: "6px 10px", borderRadius: THEME.borderRadius.sm, border: "1px solid var(--border-color)", fontSize: "13px", outline: "none", background: "var(--hover-bg)", color: "var(--text-primary)" }}
              />
              <span style={{ color: "var(--text-muted)", fontSize: "12px" }}>to</span>
              <input
                type="date"
                value={customEndDate}
                onChange={(e) => setCustomEndDate(e.target.value)}
                style={{ padding: "6px 10px", borderRadius: THEME.borderRadius.sm, border: "1px solid var(--border-color)", fontSize: "13px", outline: "none", background: "var(--hover-bg)", color: "var(--text-primary)" }}
              />
              <button
                onClick={() => {
                  if (customStartDate && customEndDate) {
                    loadAnalyticsData();
                  }
                }}
                disabled={!customStartDate || !customEndDate}
                style={{ padding: "6px 12px", borderRadius: THEME.borderRadius.sm, border: "none", background: THEME.colors.primary, color: "white", fontSize: "12px", fontWeight: "500", cursor: (!customStartDate || !customEndDate) ? "not-allowed" : "pointer", opacity: (!customStartDate || !customEndDate) ? 0.5 : 1 }}
              >
                Apply
              </button>
              <button
                onClick={() => setShowCustomPicker(false)}
                style={{ padding: "6px 10px", borderRadius: THEME.borderRadius.sm, border: "none", background: "transparent", color: "var(--text-muted)", fontSize: "12px", cursor: "pointer" }}
              >
                <X size={14} />
              </button>
            </div>
          )}
          <div style={{ display: "flex", gap: THEME.spacing.sm }}>
            <button onClick={exportXLSX} style={{ display: "flex", alignItems: "center", gap: THEME.spacing.sm, padding: "10px 16px", borderRadius: THEME.borderRadius.md, border: "1px solid var(--border-color)", background: "var(--bg-card)", color: "var(--text-primary)", fontSize: "13px", fontWeight: "500", cursor: "pointer" }}>
              <FileSpreadsheet size={16} /> Export XLSX
            </button>
            <button onClick={exportPDF} style={{ display: "flex", alignItems: "center", gap: THEME.spacing.sm, padding: "10px 16px", borderRadius: THEME.borderRadius.md, border: "1px solid var(--border-color)", background: "var(--bg-card)", color: "var(--text-primary)", fontSize: "13px", fontWeight: "500", cursor: "pointer" }}>
              <FileText size={16} /> Export PDF
            </button>
          </div>
        </div>
      </div>

      {/* Executive AI Summary */}
      <ExecutiveSummary metrics={metrics} timeRange={timeRange} />

      {/* Business Health Score & Revenue Forecast */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: THEME.spacing.xl, marginBottom: THEME.spacing.xl }}>
        <BusinessHealthScore metrics={metrics} />
        <RevenueForecast revenueChart={revenueChart} timeRange={timeRange} />
      </div>

      {/* Enhanced KPI Cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: THEME.spacing.xl, marginBottom: THEME.spacing.xl }}>
        <EnhancedKpiCard label="Total Revenue" value={fmt(metrics.total_revenue)} delta={revenueChange} target={100000} icon={DollarSign} color={THEME.colors.revenue} previousValue={fmt(revenueChart.at(-2)?.value || 0)} />
        <EnhancedKpiCard label="Active Users" value={numFmt(metrics.active_users)} delta={userChange} target={500} icon={Users} color={THEME.colors.users} previousValue={numFmt(userChart.at(-2)?.value || 0)} />
        <EnhancedKpiCard label="Conversion Rate" value={pctFmt(metrics.conversion_rate)} delta={conversionChange} target={5} icon={Target} color={THEME.colors.conversion} previousValue={pctFmt(conversionChart.at(-2)?.value || 0)} />
        <EnhancedKpiCard label="Growth Rate" value={pctFmt(metrics.growth_rate)} delta={growthChange} target={10} icon={TrendingUp} color={THEME.colors.growth} previousValue={pctFmt(growthChart.at(-2)?.value || 0)} />
      </div>

      {/* Charts + AI */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 400px", gap: THEME.spacing.xl, marginBottom: THEME.spacing.xl }}>
        <div style={{ display: "flex", flexDirection: "column", gap: THEME.spacing.xl }}>
          <ChartCard title="Revenue Trend" subtitle={RANGE_LABELS[timeRange]}>
            <ResponsiveContainer width="100%" height={280}>
              <AreaChart data={revenueChart}>
                <defs>
                  <linearGradient id="revenueGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={THEME.colors.revenue} stopOpacity={0.3} />
                    <stop offset="95%" stopColor={THEME.colors.revenue} stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                <XAxis dataKey="date" tick={{ fontSize: 12, fill: "var(--text-muted)" }} axisLine={{ stroke: "var(--border-color)" }} tickLine={false} />
                <YAxis tick={{ fontSize: 12, fill: "var(--text-muted)" }} axisLine={false} tickLine={false} tickFormatter={(v) => `₱${v >= 1000 ? (v / 1000).toFixed(0) + "k" : v}`} />
                <Tooltip contentStyle={tooltipStyle} formatter={(v) => [fmt(v), "Revenue"]} />
                <Area type="monotone" dataKey="value" stroke={THEME.colors.revenue} strokeWidth={2} fill="url(#revenueGrad)" dot={{ r: 4, strokeWidth: 2, fill: "white" }} activeDot={{ r: 6 }} />
              </AreaChart>
            </ResponsiveContainer>
          </ChartCard>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: THEME.spacing.xl }}>
            <ChartCard title="Conversion Rate" subtitle={RANGE_LABELS[timeRange]}>
              <ResponsiveContainer width="100%" height={220}>
                <AreaChart data={conversionChart}>
                  <defs><linearGradient id="convGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={THEME.colors.conversion} stopOpacity={0.3} /><stop offset="95%" stopColor={THEME.colors.conversion} stopOpacity={0} /></linearGradient></defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                  <XAxis dataKey="date" tick={{ fontSize: 11, fill: "var(--text-muted)" }} axisLine={{ stroke: "var(--border-color)" }} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: "var(--text-muted)" }} axisLine={false} tickLine={false} tickFormatter={(v) => `${Number(v).toFixed(1)}%`} />
                  <Tooltip contentStyle={tooltipStyle} formatter={(v) => [`${Number(v).toFixed(2)}%`, "Conversion Rate"]} />
                  <Area type="monotone" dataKey="value" stroke={THEME.colors.conversion} strokeWidth={2} fill="url(#convGrad)" dot={{ r: 3, strokeWidth: 2, fill: "white" }} activeDot={{ r: 5 }} />
                </AreaChart>
              </ResponsiveContainer>
            </ChartCard>
            <ChartCard title="Growth Rate" subtitle={RANGE_LABELS[timeRange]}>
              <ResponsiveContainer width="100%" height={220}>
                <AreaChart data={growthChart}>
                  <defs><linearGradient id="growthGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={THEME.colors.growth} stopOpacity={0.3} /><stop offset="95%" stopColor={THEME.colors.growth} stopOpacity={0} /></linearGradient></defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                  <XAxis dataKey="date" tick={{ fontSize: 11, fill: "var(--text-muted)" }} axisLine={{ stroke: "var(--border-color)" }} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: "var(--text-muted)" }} axisLine={false} tickLine={false} tickFormatter={(v) => `${Number(v).toFixed(1)}%`} />
                  <Tooltip contentStyle={tooltipStyle} formatter={(v) => [`${Number(v).toFixed(2)}%`, "Growth Rate"]} />
                  <Area type="monotone" dataKey="value" stroke={THEME.colors.growth} strokeWidth={2} fill="url(#growthGrad)" dot={{ r: 3, strokeWidth: 2, fill: "white" }} activeDot={{ r: 5 }} />
                </AreaChart>
              </ResponsiveContainer>
            </ChartCard>
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: THEME.spacing.xl }}>
          <div style={{ height: "500px" }}>
            <AiInsightsPanel metrics={metrics} revenueChart={revenueChart} conversionChart={conversionChart} userChart={userChart} growthChart={growthChart} timeRange={timeRange} />
          </div>
          <ActivityFeed />
        </div>
      </div>

      {/* AI Recommendations */}
      <div style={{ marginBottom: THEME.spacing.xl }}>
        <AIRecommendations metrics={metrics} timeRange={timeRange} />
      </div>

      {/* User Analytics Section */}
      <div style={{ marginTop: "24px" }}>
        <h2 style={{ fontSize: "20px", fontWeight: "600", color: "var(--text-primary)", margin: "0 0 20px 0" }}>User Overview</h2>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", marginBottom: "24px" }}>
          <KpiCard label="Total Users" value={numFmt(userStats.totalUsers)} delta={userStats.userGrowthRate} icon={Users} color={THEME.colors.users} />
          <KpiCard label="New Users This Month" value={numFmt(userStats.newUsersThisMonth)} delta={userStats.newUsersThisMonth > 0 ? 100 : 0} icon={Zap} color={THEME.colors.conversion} />
          <KpiCard label="User Growth Rate" value={pctFmt(userStats.userGrowthRate)} delta={userStats.userGrowthRate} icon={TrendingUp} color={THEME.colors.growth} />
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
          <ChartCard title="User Roles" subtitle="Distribution by role">
            <ResponsiveContainer width="100%" height={200}>
              <RePieChart>
                <Pie
                  data={userStats.roleDistribution.length > 0 ? userStats.roleDistribution : [{ name: "No Data", value: 1 }]}
                  cx="50%" cy="50%" innerRadius={50} outerRadius={80} paddingAngle={4} dataKey="value"
                >
                  {(userStats.roleDistribution.length > 0 ? userStats.roleDistribution : [{ name: "No Data", value: 1 }]).map((_, i) => (
                    <Cell key={i} fill={TRAFFIC_COLORS[i % TRAFFIC_COLORS.length]} stroke="none" />
                  ))}
                </Pie>
                <Tooltip contentStyle={tooltipStyle} formatter={(v, n) => [`${v} users`, n]} />
              </RePieChart>
            </ResponsiveContainer>
            <div style={{ display: "flex", justifyContent: "center", gap: "12px", marginTop: "8px", flexWrap: "wrap" }}>
              {userStats.roleDistribution.map((role, i) => (
                <div key={role.name} style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                  <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: TRAFFIC_COLORS[i % TRAFFIC_COLORS.length] }} />
                  <span style={{ fontSize: "11px", color: "var(--text-secondary)" }}>{role.name} ({role.value})</span>
                </div>
              ))}
            </div>
          </ChartCard>
          <ChartCard title="New Registrations" subtitle="Last 30 days">
            <ResponsiveContainer width="100%" height={200}>
              <AreaChart data={userStats.registrationTrend}>
                <defs><linearGradient id="regGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={THEME.colors.primary} stopOpacity={0.3} /><stop offset="95%" stopColor={THEME.colors.primary} stopOpacity={0} /></linearGradient></defs>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                <XAxis dataKey="date" tick={{ fontSize: 9, fill: "#94a3b8" }} axisLine={false} tickLine={false} tickFormatter={(v) => v.slice(5)} />
                <YAxis tick={{ fontSize: 9, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
                <Tooltip contentStyle={tooltipStyle} formatter={(v) => [`${v} new users`, "Registrations"]} />
                <Area type="monotone" dataKey="value" stroke={THEME.colors.primary} strokeWidth={2} fill="url(#regGrad)" dot={false} />
              </AreaChart>
            </ResponsiveContainer>
          </ChartCard>
        </div>

        {/* Full user table — paginated client-side */}
        <UserTable userList={userList} loading={userTableLoading} />
      </div>
    </div>
  );
}
