export const DEFAULT_THEME_COLORS = {
  page_background_color: "#020617",
  section_background_color: "#0f172a",
  hero_background_color: "#020617",
  hero_gradient_from: "",
  hero_gradient_to: "",
  hero_text_color: "#ffffff",
  hero_muted_text_color: "#cbd5e1",
  heading_color: "#ffffff",
  body_text_color: "#cbd5e1",
  card_background_color: "rgba(255,255,255,0.04)",
  card_border_color: "rgba(255,255,255,0.10)",
};

function buildAdvancedStyles({
  page,
  sections,
  cards,
  text,
  buttons,
  badges,
  icons,
}) {
  return {
    page: {
      backgroundColor: page.backgroundColor,
    },
    sections: {
      services: {
        backgroundColor: sections.servicesBackground,
      },
      booking: {
        backgroundColor: sections.bookingBackground,
      },
    },
    cards: {
      default: {
        backgroundColor: cards.backgroundColor,
        borderColor: cards.borderColor,
      },
    },
    text: {
      hero_brand_title: {
        color: text.heroText,
      },
      hero_badge: {
        color: text.badgeText,
      },
      hero_headline: {
        color: text.heroHeadline,
      },
      hero_subheadline: {
        color: text.heroSubheadline,
      },
      services_heading: {
        color: text.sectionHeading,
      },
      services_description: {
        color: text.sectionBody,
      },
      service_card_title: {
        color: text.cardTitle,
      },
      service_card_description: {
        color: text.cardBody,
      },
      booking_heading: {
        color: text.sectionHeading,
      },
      booking_description: {
        color: text.sectionBody,
      },
    },
    buttons: {
      primary: {
        backgroundColor: buttons.primaryBackground,
        color: buttons.primaryText,
        borderColor: buttons.primaryBorder || buttons.primaryBackground,
      },
      secondary: {
        backgroundColor: buttons.secondaryBackground,
        color: buttons.secondaryText,
        borderColor: buttons.secondaryBorder,
      },
    },
    badges: {
      default: {
        backgroundColor: badges.backgroundColor,
        color: badges.color,
        borderColor: badges.borderColor,
      },
      hero_badge: {
        backgroundColor: badges.heroBackgroundColor,
        color: badges.heroColor,
        borderColor: badges.heroBorderColor,
        borderRadius: "999px",
      },
    },
    icons: {
      hero_logo: {
        backgroundColor: icons.heroLogoBackground,
        color: icons.heroLogoText,
        borderRadius: "16px",
      },
    },
  };
}

const EXECUTIVE_DARK_ADVANCED_STYLES = buildAdvancedStyles({
  page: {
    backgroundColor: "#020617",
  },
  sections: {
    servicesBackground: "#0f172a",
    bookingBackground: "#020617",
  },
  cards: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderColor: "rgba(255,255,255,0.12)",
  },
  text: {
    heroText: "#ffffff",
    badgeText: "#facc15",
    heroHeadline: "#ffffff",
    heroSubheadline: "#cbd5e1",
    sectionHeading: "#ffffff",
    sectionBody: "#cbd5e1",
    cardTitle: "#ffffff",
    cardBody: "#cbd5e1",
  },
  buttons: {
    primaryBackground: "#d4af37",
    primaryText: "#020617",
    secondaryBackground: "rgba(255,255,255,0.08)",
    secondaryText: "#ffffff",
    secondaryBorder: "rgba(255,255,255,0.18)",
  },
  badges: {
    backgroundColor: "rgba(212,175,55,0.12)",
    color: "#facc15",
    borderColor: "rgba(212,175,55,0.34)",
    heroBackgroundColor: "rgba(212,175,55,0.14)",
    heroColor: "#facc15",
    heroBorderColor: "rgba(212,175,55,0.36)",
  },
  icons: {
    heroLogoBackground: "#d4af37",
    heroLogoText: "#020617",
  },
});

const INSURANCE_BLUE_ADVANCED_STYLES = buildAdvancedStyles({
  page: {
    backgroundColor: "#ffffff",
  },
  sections: {
    servicesBackground: "#eaf6ff",
    bookingBackground: "#ffffff",
  },
  cards: {
    backgroundColor: "#ffffff",
    borderColor: "#cfe5f8",
  },
  text: {
    heroText: "#ffffff",
    badgeText: "#ff8a1d",
    heroHeadline: "#ffffff",
    heroSubheadline: "#eaf6ff",
    sectionHeading: "#2f3f9f",
    sectionBody: "#334155",
    cardTitle: "#2f3f9f",
    cardBody: "#475569",
  },
  buttons: {
    primaryBackground: "#ff8a1d",
    primaryText: "#ffffff",
    secondaryBackground: "#ffffff",
    secondaryText: "#2f3f9f",
    secondaryBorder: "#ffffff",
  },
  badges: {
    backgroundColor: "#ffffff",
    color: "#2f3f9f",
    borderColor: "#cfe5f8",
    heroBackgroundColor: "#111827",
    heroColor: "#ff8a1d",
    heroBorderColor: "#111827",
  },
  icons: {
    heroLogoBackground: "#111827",
    heroLogoText: "#ffffff",
  },
});

const CLEAN_LIGHT_ADVANCED_STYLES = buildAdvancedStyles({
  page: {
    backgroundColor: "#ffffff",
  },
  sections: {
    servicesBackground: "#f8fafc",
    bookingBackground: "#ffffff",
  },
  cards: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
  },
  text: {
    heroText: "#0f172a",
    badgeText: "#2563eb",
    heroHeadline: "#0f172a",
    heroSubheadline: "#475569",
    sectionHeading: "#0f172a",
    sectionBody: "#475569",
    cardTitle: "#0f172a",
    cardBody: "#64748b",
  },
  buttons: {
    primaryBackground: "#2563eb",
    primaryText: "#ffffff",
    secondaryBackground: "#ffffff",
    secondaryText: "#1e40af",
    secondaryBorder: "#bfdbfe",
  },
  badges: {
    backgroundColor: "#eff6ff",
    color: "#1d4ed8",
    borderColor: "#bfdbfe",
    heroBackgroundColor: "#eff6ff",
    heroColor: "#2563eb",
    heroBorderColor: "#bfdbfe",
  },
  icons: {
    heroLogoBackground: "#2563eb",
    heroLogoText: "#ffffff",
  },
});

const LUXURY_GOLD_ADVANCED_STYLES = buildAdvancedStyles({
  page: {
    backgroundColor: "#030712",
  },
  sections: {
    servicesBackground: "#111827",
    bookingBackground: "#030712",
  },
  cards: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderColor: "rgba(234,179,8,0.22)",
  },
  text: {
    heroText: "#ffffff",
    badgeText: "#facc15",
    heroHeadline: "#ffffff",
    heroSubheadline: "#d1d5db",
    sectionHeading: "#ffffff",
    sectionBody: "#d1d5db",
    cardTitle: "#ffffff",
    cardBody: "#d1d5db",
  },
  buttons: {
    primaryBackground: "#eab308",
    primaryText: "#111827",
    secondaryBackground: "rgba(234,179,8,0.10)",
    secondaryText: "#facc15",
    secondaryBorder: "rgba(234,179,8,0.35)",
  },
  badges: {
    backgroundColor: "rgba(234,179,8,0.12)",
    color: "#facc15",
    borderColor: "rgba(234,179,8,0.35)",
    heroBackgroundColor: "rgba(234,179,8,0.14)",
    heroColor: "#facc15",
    heroBorderColor: "rgba(234,179,8,0.40)",
  },
  icons: {
    heroLogoBackground: "#eab308",
    heroLogoText: "#111827",
  },
});

const CLINIC_BLUE_ADVANCED_STYLES = buildAdvancedStyles({
  page: {
    backgroundColor: "#eef8ff",
  },
  sections: {
    servicesBackground: "#ffffff",
    bookingBackground: "#f0f9ff",
  },
  cards: {
    backgroundColor: "#ffffff",
    borderColor: "#bae6fd",
  },
  text: {
    heroText: "#0f172a",
    badgeText: "#0284c7",
    heroHeadline: "#0f172a",
    heroSubheadline: "#334155",
    sectionHeading: "#075985",
    sectionBody: "#475569",
    cardTitle: "#075985",
    cardBody: "#475569",
  },
  buttons: {
    primaryBackground: "#0ea5e9",
    primaryText: "#ffffff",
    secondaryBackground: "#ffffff",
    secondaryText: "#0369a1",
    secondaryBorder: "#bae6fd",
  },
  badges: {
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    borderColor: "#bae6fd",
    heroBackgroundColor: "#e0f2fe",
    heroColor: "#0369a1",
    heroBorderColor: "#bae6fd",
  },
  icons: {
    heroLogoBackground: "#0ea5e9",
    heroLogoText: "#ffffff",
  },
});

export const LANDING_THEME_PRESETS = [
  {
    id: "executive_navy",
    name: "Executive Dark",
    description: "Premium navy and gold for professional service brands.",
    theme_mode: "dark",
    primary_color: "#d4af37",
    secondary_color: "#0f172a",
    theme: {
      preset_id: "executive_navy",
      preset_name: "Executive Dark",
      page_background_color: "#020617",
      section_background_color: "#0f172a",
      hero_background_color: "#020617",
      hero_gradient_from: "#020617",
      hero_gradient_to: "#0f172a",
      hero_text_color: "#ffffff",
      hero_muted_text_color: "#cbd5e1",
      heading_color: "#ffffff",
      body_text_color: "#cbd5e1",
      accent_color: "#d4af37",
      card_background_color: "rgba(255,255,255,0.06)",
      card_border_color: "rgba(255,255,255,0.12)",
      blue_section_background: "#0f172a",
      light_section_background: "#111827",
      dark_footer_background: "#020617",
      section_pattern: ["default", "default", "default"],
      button_style: "gold_solid",
      card_style: "glass",
      border_radius: "large",
    },
    advancedStyles: EXECUTIVE_DARK_ADVANCED_STYLES,
    preview: {
      bg: "bg-slate-900",
      accent: "bg-yellow-500",
      line1: "bg-slate-300",
      line2: "bg-slate-500",
      button: "bg-yellow-500",
      sectionA: "bg-slate-900",
      sectionB: "bg-slate-800",
      card: "bg-white/10",
    },
  },
  {
    id: "insurance_blue_premium",
    name: "Insurance Blue Premium",
    description:
      "InLife-inspired blue, white, and orange layout with alternating section backgrounds.",
    theme_mode: "light",
    primary_color: "#ff8a1d",
    secondary_color: "#2f3f9f",
    theme: {
      preset_id: "insurance_blue_premium",
      preset_name: "Insurance Blue Premium",
      page_background_color: "#ffffff",
      section_background_color: "#eaf6ff",
      hero_background_color: "#2498df",
      hero_gradient_from: "#3bb7f0",
      hero_gradient_to: "#1878c8",
      hero_text_color: "#ffffff",
      hero_muted_text_color: "#eaf6ff",
      heading_color: "#2f3f9f",
      body_text_color: "#334155",
      accent_color: "#ff8a1d",
      card_background_color: "#ffffff",
      card_border_color: "#cfe5f8",
      blue_section_background: "#1688d4",
      light_section_background: "#eaf6ff",
      dark_footer_background: "#2f3f9f",
      section_pattern: [
        "blue",
        "white",
        "blue",
        "white",
        "light_blue",
        "white",
        "deep_blue",
      ],
      button_style: "orange_primary_white_secondary",
      card_style: "soft_white_glass",
      border_radius: "large",
    },
    advancedStyles: INSURANCE_BLUE_ADVANCED_STYLES,
    preview: {
      bg: "bg-sky-500",
      accent: "bg-orange-500",
      line1: "bg-white",
      line2: "bg-blue-100",
      button: "bg-orange-500",
      sectionA: "bg-white",
      sectionB: "bg-sky-500",
      card: "bg-white",
    },
  },
  {
    id: "clean_light",
    name: "Clean Light",
    description: "Bright, simple, and easy to read for general businesses.",
    theme_mode: "light",
    primary_color: "#2563eb",
    secondary_color: "#f8fafc",
    theme: {
      preset_id: "clean_light",
      preset_name: "Clean Light",
      page_background_color: "#ffffff",
      section_background_color: "#f8fafc",
      hero_background_color: "#ffffff",
      hero_gradient_from: "#ffffff",
      hero_gradient_to: "#f8fafc",
      hero_text_color: "#0f172a",
      hero_muted_text_color: "#475569",
      heading_color: "#0f172a",
      body_text_color: "#475569",
      accent_color: "#2563eb",
      card_background_color: "#ffffff",
      card_border_color: "#e2e8f0",
      blue_section_background: "#eff6ff",
      light_section_background: "#f8fafc",
      dark_footer_background: "#0f172a",
      section_pattern: ["white", "light_blue", "white"],
      button_style: "blue_primary_white_secondary",
      card_style: "soft_white",
      border_radius: "large",
    },
    advancedStyles: CLEAN_LIGHT_ADVANCED_STYLES,
    preview: {
      bg: "bg-white",
      accent: "bg-blue-600",
      line1: "bg-slate-100",
      line2: "bg-slate-100",
      button: "bg-blue-600",
      sectionA: "bg-white",
      sectionB: "bg-slate-100",
      card: "bg-white",
    },
  },
  {
    id: "prestige_gold",
    name: "Luxury Gold",
    description: "Dark luxury style with stronger gold accents.",
    theme_mode: "dark",
    primary_color: "#eab308",
    secondary_color: "#111827",
    theme: {
      preset_id: "prestige_gold",
      preset_name: "Luxury Gold",
      page_background_color: "#030712",
      section_background_color: "#111827",
      hero_background_color: "#030712",
      hero_gradient_from: "#030712",
      hero_gradient_to: "#111827",
      hero_text_color: "#ffffff",
      hero_muted_text_color: "#d1d5db",
      heading_color: "#ffffff",
      body_text_color: "#d1d5db",
      accent_color: "#eab308",
      card_background_color: "rgba(255,255,255,0.07)",
      card_border_color: "rgba(234,179,8,0.22)",
      blue_section_background: "#111827",
      light_section_background: "#1f2937",
      dark_footer_background: "#030712",
      section_pattern: ["default", "default", "default"],
      button_style: "gold_solid",
      card_style: "luxury_glass",
      border_radius: "large",
    },
    advancedStyles: LUXURY_GOLD_ADVANCED_STYLES,
    preview: {
      bg: "bg-slate-950",
      accent: "bg-yellow-500",
      line1: "bg-slate-300",
      line2: "bg-slate-500",
      button: "bg-yellow-500",
      sectionA: "bg-slate-950",
      sectionB: "bg-slate-800",
      card: "bg-white/10",
    },
  },
  {
    id: "clinic_clean",
    name: "Clinic Blue",
    description: "Clean blue style for clinics, consultants, and service teams.",
    theme_mode: "light",
    primary_color: "#0ea5e9",
    secondary_color: "#f8fafc",
    theme: {
      preset_id: "clinic_clean",
      preset_name: "Clinic Blue",
      page_background_color: "#eef8ff",
      section_background_color: "#ffffff",
      hero_background_color: "#ffffff",
      hero_gradient_from: "#ffffff",
      hero_gradient_to: "#e0f2fe",
      hero_text_color: "#0f172a",
      hero_muted_text_color: "#334155",
      heading_color: "#075985",
      body_text_color: "#475569",
      accent_color: "#0ea5e9",
      card_background_color: "#ffffff",
      card_border_color: "#bae6fd",
      blue_section_background: "#e0f2fe",
      light_section_background: "#f0f9ff",
      dark_footer_background: "#075985",
      section_pattern: ["white", "light_blue", "white"],
      button_style: "blue_primary_white_secondary",
      card_style: "clinic_soft",
      border_radius: "large",
    },
    advancedStyles: CLINIC_BLUE_ADVANCED_STYLES,
    preview: {
      bg: "bg-white",
      accent: "bg-sky-500",
      line1: "bg-slate-100",
      line2: "bg-slate-100",
      button: "bg-sky-500",
      sectionA: "bg-white",
      sectionB: "bg-sky-100",
      card: "bg-white",
    },
  },
];
